#!/bin/sh -e

export TZ=/etc/localtime

[ -f /etc/default/udev ] && . /etc/default/udev

echo "Caching udev devnodes"

if [ "$DEVCACHE" != "" ]; then
	echo -n "Populating dev cache"
	(cd /; tar cf $DEVCACHE dev)
	[ -x /bin/uname ] && /bin/uname -mrspv > /etc/udev/saved.uname || touch /etc/udev/saved.uname
	[ -r /proc/cmdline ] && cat /proc/cmdline > /etc/udev/saved.cmdline || touch /etc/udev/saved.cmdline
	[ -r /proc/devices ] && cat /proc/devices > /etc/udev/saved.devices || touch /etc/udev/saved.devices
	[ -r /proc/atags ] && cat /proc/atags > /etc/udev/saved.atags || touch /etc/udev/saved.atags
	echo
fi

exit 0
