#!/bin/sh -e

export TZ=/etc/localtime

[ -f /etc/default/udev ] && . /etc/default/udev

echo "Caching udev devnodes"

if [ "$DEVCACHE" != "" ]; then
	echo -n "Populating dev cache"
	(cd /; tar cf $DEVCACHE dev)
	mv /dev/shm/uname /etc/udev/saved.uname
	mv /dev/shm/cmdline /etc/udev/saved.cmdline
	mv /dev/shm/devices /etc/udev/saved.devices
	mv /dev/shm/atags /etc/udev/saved.atags
	echo
else
	rm -f /dev/shm/uname
	rm -f /dev/shm/cmdline
	rm -f /dev/shm/devices
	rm -f /dev/shm/atags
fi

exit 0
