COLLIE_MEMORY_SIZE = "58"
COLLIE_RAMDISK_SIZE = "6"
KERNEL_CONSOLE = "tty0"

require ../linux/openzaurus-sa_2.4.18-rmk7-pxa3-embedix20030509.bb

KERNEL_IMAGE_BASE_NAME = "${KERNEL_IMAGETYPE}-${MACHINE}-${COLLIE_MEMORY_SIZE}-${COLLIE_RAMDISK_SIZE}-DEBUG-${DATETIME}.bin"
KERNEL_IMAGE_SYMLINK_NAME = "${KERNEL_IMAGETYPE}-${MACHINE}-${COLLIE_MEMORY_SIZE}-${COLLIE_RAMDISK_SIZE}-DEBUG.bin"
