#!/usr/bin/env python

# generate Python Manifest for the OpenEmbedded build system
# (C) 2002-2006 Michael Lauer <mickey@Vanille.de>
# MIT license

import os
import sys
import time

# major version
VERSION = "2.4.0"
# increase when touching python-core
BASEREV = 1

__author__ = "Michael 'Mickey' Lauer <mickey@Vanille.de>"
__version__ = "$Revision: 1.6 $"

class MakefileMaker:

    def __init__( self, outfile ):
        """initialize"""
        self.packages = {}
        self.sourcePrefix = "/lib/python%s/" % VERSION[:3]
        self.targetPrefix = "${libdir}/python%s" % VERSION[:3]
        self.output = outfile
        self.out( "### AUTO-GENERATED by '%s' [(C) 2002-2006 Michael Lauer] on %s" % ( sys.argv[0], time.asctime() ) )
        self.out( "###" )
        self.out( "### Warning: Manual edits will be lost!" )
        self.out( "###" )
    #
    # helper functions
    #

    def out( self, data ):
        """print a line to the output file"""
        print >> self.output, data

    def setPrefix( self, sourcePrefix, targetPrefix ):
        """set a file prefix for addPackage files"""
        self.sourcePrefix = sourcePrefix
        self.targetPrefix = targetPrefix

    def doProlog( self ):
        self.out( """ """ )
        self.out( "" )

    def addPackage( self, revision, name, description, dependencies, filenames ):
        """add a package to the Makefile"""
        if type( filenames ) == type( "" ):
            filenames = filenames.split()
        fullFilenames = []
        for filename in filenames:
            if filename[0] != "/":
                fullFilenames.append( ( "%s%s" % ( self.sourcePrefix, filename ), "%s%s" % ( self.targetPrefix, filename ) ) )
            else:
                fullFilenames.append( ( filename, filename ) )
        self.packages[name] = revision, description, dependencies, fullFilenames

    def doBody( self ):
        """generate body of Makefile"""

        global VERSION

        #
        # generate package line
        #

        packageLine = 'PACKAGES="'
        for name in self.packages:
            packageLine += "%s " % name
        packageLine += '"'

        self.out( packageLine )
        self.out( "" )

        #
        # generate package variables
        #

        for name, data in self.packages.iteritems():
            rev, desc, deps, files = data

            #
            # write out the description, revision and dependencies
            #
            self.out( 'DESCRIPTION_%s="%s"' % ( name, desc ) )
            self.out( 'PR_%s="ml%d"' % ( name, rev + BASEREV ) )
            self.out( 'RDEPENDS_%s="%s"' % ( name, deps.replace( ",", "" ) ) )

            line = 'FILES_%s="' % name

            #
            # check which directories to make in the temporary directory
            #

            dirset = {} # if python had a set-datatype this would be sufficient. for now, we're using a dict instead.
            for source, target in files:
                dirset[os.path.dirname( target )] = True

            #
            # generate which files to copy for the target (-dfR because whole directories are also allowed)
            #

            for source, target in files:
                line += "%s " % target

            line += '"'
            self.out( line )

#            for source, target in files:
#                if ( source.find( "lib-dynload" ) != -1 ) or \
#                  ( source.endswith( "python" ) ) or \
#                   ( source.endswith( "pydoc" ) ): # MACHDEP
#                    self.out( "\t cp -dfR $(STAGING_LIBDIR)/..%s $(IPKTMP_DIR)%s/;" % ( source, os.path.dirname( target ) ) )
#                else:
#                    self.out( "\t cp -dfR $(STAGING_DIR)%s $(IPKTMP_DIR)%s/;" % ( source, os.path.dirname( target ) ) )
#
            self.out( "" )

    def doEpilog( self ):
        self.out( """""" )
        self.out( "" )

    def make( self ):
        self.doProlog()
        self.doBody()
        self.doEpilog()

if __name__ == "__main__":

    if len( sys.argv ) > 1:
        os.popen( "rm -f ./%s" % sys.argv[1] )
        outfile = file( sys.argv[1], "w" )
    else:
        outfile = sys.stdout

    m = MakefileMaker( outfile )

    # Add packages here.
    # Note: Only supply dlopen link library dependencies here. Aautomatic link libraries are getting added by the shlibs dependency code

    m.setPrefix( "/", "/usr/" )

    m.addPackage( 1, "python-core", "Python Interpreter and core modules (needed!)", "",
    "lib/python2.4/__future__.* lib/python2.4/copy.* lib/python2.4/copy_reg.* lib/python2.4/ConfigParser.py " +
    "lib/python2.4/getopt.* lib/python2.4/new.* " +
    "lib/python2.4/os.* lib/python2.4/posixpath.* "+
    "lib/python2.4/warnings.* lib/python2.4/site.* lib/python2.4/stat.* lib/python2.4/UserDict.* " +
    "lib/python2.4/lib-dynload/binascii.so lib/python2.4/lib-dynload/struct.so lib/python2.4/lib-dynload/time.so " +
    "lib/python2.4/lib-dynload/xreadlines.so lib/python2.4/types.* bin/python" )

    m.addPackage( 1, "python-pydoc", "Python Interactive Help Support", "python-core, python-lang, python-stringold, python-re",
    "bin/pydoc lib/python2.4/pydoc.*" )

    m.setPrefix( "/lib/python2.4/", "${libdir}/python2.4/" )

    m.addPackage( 1, "python-audio", "Python Audio Handling", "python-core",
    "wave.* chunk.* lib-dynload/ossaudiodev.so lib-dynload/audioop.so" )

    m.addPackage( 1, "python-codecs", "Python Codecs, Encodings & i18n Support", "python-core",
    "codecs.* encodings locale.* lib-dynload/_locale.so lib-dynload/unicodedata.so gettext.* xdrlib.*" )

    m.addPackage( 1, "python-compile", "Python Bytecode Compilation Support", "python-core",
    "py_compile.* compileall.*" )

    m.addPackage( 1, "python-compiler", "Python Compiler Support", "python-core",
    "compiler" ) # package

    m.addPackage( 1, "python-compression", "Python High Level Compression Support", "python-core, python-zlib",
    "gzip.* zipfile.*" )

    m.addPackage( 1, "python-crypt", "Python Basic Cryptographic and Hashing Support", "python-core",
    "lib-dynload/crypt.so lib-dynload/md5.so lib-dynload/rotor.so lib-dynload/sha.so" )

    m.addPackage( 1, "python-textutils", "Python Option Parsing, Text Wrapping and Comma-Separated-Value Support", "python-core, python-io, python-re, python-stringold",
    "lib-dynload/_csv.so csv.* optparse.* textwrap.*" )

    m.addPackage( 1, "python-curses", "Python Curses Support", "python-core",
    "curses lib-dynload/_curses.so lib-dynload/_curses_panel.so" ) # package

    m.addPackage( 1, "python-db", "Python File-Based Database Support", "python-core",
    "anydbm.* dumbdbm.* whichdb.* " )

    m.addPackage( 1, "python-distutils", "Python Distribution Utility", "python-core",
    "distutils" ) # package

    m.addPackage( 1, "python-email", "Python Email Support", "python-core, python-io, python-re",
    "email" ) # package

    m.addPackage( 1, "python-fcntl", "Python's fcntl Interface", "python-core",
    "lib-dynload/fcntl.so" )

    m.addPackage( 1, "python-hotshot", "Python Hotshot Profiler", "python-core",
    "hotshot lib-dynload/_hotshot.so" )

    m.addPackage( 1, "python-html", "Python HTML Processing", "python-core",
    "formatter.* htmlentitydefs.* htmllib.* markupbase.* sgmllib.* " )

    m.addPackage( 1, "python-gdbm", "Python GNU Database Support", "python-core, libgdbm3",
    "lib-dynload/gdbm.so" )

    m.addPackage( 1, "python-image", "Python Graphical Image Handling", "python-core",
    "colorsys.* imghdr.* lib-dynload/imageop.so lib-dynload/rgbimg.so" )

    m.addPackage( 1, "python-io", "Python Low-Level I/O", "python-core, python-math",
    "lib-dynload/_socket.so lib-dynload/select.so lib-dynload/termios.so lib-dynload/cStringIO.so pipes.* socket.* tempfile.* StringIO.* " )

    m.addPackage( 2, "python-lang", "Python Low-Level Language Support", "python-core",
    "lib-dynload/array.so lib-dynload/parser.so lib-dynload/operator.so lib-dynload/_weakref.so " +
    "lib-dynload/itertools.so lib-dynload/collections.so " +
    "atexit.* code.* codeop.* dis.* inspect.* keyword.* opcode.* repr.* token.* tokenize.* traceback.* linecache.* weakref.*" )

    m.addPackage( 2, "python-math", "Python Math Support", "python-core",
    "lib-dynload/cmath.so lib-dynload/math.so lib-dynload/_random.so random.* sets.*" )

    m.addPackage( 1, "python-mime", "Python MIME Handling APIs", "python-core, python-io",
    "mimetools.* rfc822.*" )

    m.addPackage( 1, "python-mmap", "Python Memory-Mapped-File Support", "python-core, python-io",
    "lib-dynload/mmap.so " )

    m.addPackage( 1, "python-unixadmin", "Python Unix Administration Support", "python-core",
    "lib-dynload/nis.so lib-dynload/grp.so lib-dynload/pwd.so getpass.*" )

    m.addPackage( 1, "python-netclient", "Python Internet Protocol Clients", "python-core, python-io, python-mime",
    "base64.* ftplib.* gopherlib.* hmac.* httplib.* mimetypes.* nntplib.* poplib.* smtplib.* telnetlib.* urllib.* urllib2.* urlparse.*" )

    m.addPackage( 1, "python-netserver", "Python Internet Protocol Servers", "python-core, python-netclient",
    "cgi.* BaseHTTPServer.* SimpleHTTPServer.* SocketServer.*" )

    m.addPackage( 1, "python-pickle", "Python Persistence Support", "python-core, python-re",
    "pickle.* shelve.* lib-dynload/cPickle.so" )

    m.addPackage( 1, "python-pprint", "Python Pretty-Print Support", "python-core",
    "pprint.*" )

    # python-pyqt has its own subdirectory

    # python-pyxml has its own subdirectory

    m.addPackage( 1, "python-re", "Python Regular Expression APIs", "python-core, python-stringold",
    "re.* sre.* sre_compile.* sre_constants* sre_parse.*" ) # _sre is builtin

    m.addPackage( 1, "python-readline", "Python Readline Support", "python-core, libreadline4",
    "lib-dynload/readline.so rlcompleter.*" )

    m.addPackage( 1, "python-resource", "Python Resource Control Interface", "python-core",
    "lib-dynload/resource.so" )

    m.addPackage( 1, "python-shell", "Python Shell-Like Functionality", "python-core, python-re",
    "commands.* dircache.* fnmatch.* glob.* popen2.* shutil.*" )

    m.addPackage( 1, "python-stringold", "Python Deprecated String APIs", "python-core",
    "lib-dynload/strop.so string.*" )

    m.addPackage( 1, "python-syslog", "Python's syslog Interface", "python-core",
    "lib-dynload/syslog.so" )

    m.addPackage( 1, "python-terminal", "Python Terminal Controlling Support", "python-core, python-io",
    "pty.* tty.*" )

    m.addPackage( 1, "python-threading", "Python Threading & Synchronization Support", "python-core, python-lang",
    "bisect.* threading.* Queue.*" )

    m.addPackage( 1, "python-unittest", "Python Unit Testing Framework", "python-core, python-stringold, python-lang",
    "unittest.*" )

    m.addPackage( 1, "python-xml", "Python basic XML support.", "python-core, python-re",
    "lib-dynload/pyexpat.so xml xmllib.*" ) # package

    m.addPackage( 1, "python-xmlrpc", "Python XMLRPC Support", "python-core, python-xml, python-netserver, python-lang",
    "xmlrpclib.* SimpleXMLRPCServer.*" )

    m.addPackage( 2, "python-zlib", "Python zlib Support.", "python-core, libz1",
    "lib-dynload/zlib.so" )

    m.make()
