#! /bin/sh

matrixgui="/usr/bin/matrix_gui"
GUI_OPTS="/usr/share/matrix/html/menu_main.html"

test -x "$matrixgui" || exit 0

case "$1" in
  start)
    echo -n "Starting Matrix GUI application"
    start-stop-daemon --start --quiet --background --pidfile /var/run/matrix-gui.pid --exec $matrixgui -- $GUI_OPTS
    echo "."
    ;;
  stop)
    echo -n "Stopping Matrix GUI application"
    start-stop-daemon --stop --quiet --pidfile /var/run/matrix-gui.pid
    echo "."
    ;;
  *)
    echo "Usage: /etc/init.d/matrix-gui {start|stop}"
    exit 1
esac

exit 0
