#!/bin/sh
#
if [ X"$IFACE" = "Xeth0" ] ; then
  nfsroot=`grep ' / nfs ' /proc/mounts`
  if [ -n "$nfsroot" ]; then
    echo "WARNING: Refusing to ifup eth0 when booted to a nfs-mounted rootfs."
    exit 1
  fi
fi
exit 0
