Index: Makefile
===================================================================
RCS file: /cvs/gpe/base/gpe-conf/Makefile,v
retrieving revision 1.103
diff -r1.103 Makefile
9a10
> MACHINE = other
11a13,23
> 
> ifeq ($(MACHINE),ipaq)
> PACKAGE_CPPFLAGS += -DMACH_IPAQ
> PACKAGE_CFLAGS += -DMACH_IPAQ
> endif
> 
> ifeq ($(MACHINE),simpad)
> PACKAGE_CPPFLAGS += -DMACH_SIMPAD
> PACKAGE_CFLAGS += -DMACH_SIMPAD
> endif
> 
29,30c41,42
< LIBS += -L../libgpewidget -L../libxsettings  -L../libxsettings-client -L.
< CFLAGS += -Wall -I../libgpewidget -I../libxsettings-client -I../libxsettings 
---
> PACKAGE_CPPFLAGS += -I../libxsettings -I../libxsettings-client
> PACKAGE_LDFLAGS += -L../libxsettings -L../libxsettings-client
33d44
< CFLAGS += -I/usr/local/include/gpe -Wall
36a48,54
> GTKCFLAGS = `pkg-config --cflags gtk+-2.0` 
> GTKLDFLAGS = `pkg-config --libs gtk+-2.0 gdk-2.0` 
> 
> PACKAGE_CPPFLAGS += $(STANDARD_CPPFLAGS) -I.
> PACKAGE_CFLAGS += $(STANDARD_CFLAGS) $(GTKCFLAGS) $(GPECFLAGS) -I.
> PACKAGE_LDFLAGS += $(STANDARD_LDFLAGS) $(GTKLDFLAGS) $(GPELIBS) -lXsettings -lXsettings-client -lcrypt
> 
38c56
< CFLAGS += -g -DDEBUG
---
> PACKAGE_CFLAGS += -g -DDEBUG
40c58
< CFLAGS += -Os -fomit-frame-pointer
---
> PACKAGE_CFLAGS += -Os -fomit-frame-pointer
43,45c61,62
< LIBS += -lXsettings -lXsettings-client -lcrypt
< CFLAGS += -DVERSION=\"$(VERSION)\" -DPREFIX=\"$(PREFIX)\" -D_GNU_SOURCE
< CFLAGS += -DPACKAGE=\"$(PACKAGE)\" -DPACKAGE_LOCALE_DIR=\"$(PREFIX)/share/locale\"
---
> PACKAGE_CFLAGS += -DVERSION=\"$(VERSION)\" -DPREFIX=\"$(PREFIX)\" -D_GNU_SOURCE 
> PACKAGE_CFLAGS += -DPACKAGE=\"$(PACKAGE)\" -DPACKAGE_LOCALE_DIR=\"$(PREFIX)/share/locale\"
47,48d63
< GTKCFLAGS = `pkg-config --cflags gtk+-2.0` 
< GTKLDFLAGS += `pkg-config --libs gtk+-2.0 gdk-2.0` 
53,54c68,69
< STRIP=strip
< CC=gcc
---
> #STRIP=strip
> #CC=gcc
56,57c71,72
< CFLAGS += `pkg-config --cflags gtk+-2.0 gdk-pixbuf-2.0` -Wall
< LIBS += -lgpewidget `pkg-config --libs gtk+-2.0 gdk-pixbuf-2.0`
---
> #CFLAGS += `pkg-config --cflags gtk+-2.0 gdk-pixbuf-2.0` -Wall
> #LIBS += -lgpewidget `pkg-config --libs gtk+-2.0 gdk-pixbuf-2.0`
61,62c76,77
< CC=arm-linux-gcc
< STRIP=arm-linux-strip
---
> #CC=arm-linux-gcc
> #STRIP=arm-linux-strip
64,70c79,85
< CFLAGS += -march=armv4 -mtune=strongarm
< CFLAGS += `pkg-config --cflags gtk+-2.0 gdk-pixbuf-2.0` -Wall 
< LIBS += -L/skiff/local/arm-linux/lib -L/skiff/local/arm-linux/lib/X11  
< LIBS += -lgpewidget -lgtk-x11-2.0 -lgdk-x11-2.0 -latk-1.0 -lpangoxft-1.0 
< LIBS += -lpangox-1.0 -lpango-1.0 -lgdk_pixbuf-2.0 -lm -lgobject-2.0 
< LIBS += -lgmodule-2.0 -ldl -lglib-2.0 -lXinerama
< LIBS += -lX11 -lXext -lXrender -lgdk-x11-2.0
---
> #CFLAGS += -march=armv4 -mtune=strongarm
> #CFLAGS += `pkg-config --cflags gtk+-2.0 gdk-pixbuf-2.0` -Wall 
> #LIBS += -L/skiff/local/arm-linux/lib -L/skiff/local/arm-linux/lib/X11  
> #LIBS += -lgpewidget -lgtk-x11-2.0 -lgdk-x11-2.0 -latk-1.0 -lpangoxft-1.0 
> #LIBS += -lpangox-1.0 -lpango-1.0 -lgdk_pixbuf-2.0 -lm -lgobject-2.0 
> #LIBS += -lgmodule-2.0 -ldl -lglib-2.0 -lXinerama
> #LIBS += -lX11 -lXext -lXrender -lgdk-x11-2.0
74d88
< CPPFLAGS += -I.
111c125
< CFLAGS += -D PACKAGETOOL
---
> PACKAGE_CFLAGS += -D PACKAGETOOL
170c184
< 	$(CC) -g -o $@ $(OBJS) $(LIBS)
---
> 	$(CC) -g -o $@ $(OBJS) $(LDFLAGS) $(PACKAGE_LDFLAGS)
175c189
< 	$(CC) -g -o $@ $(OBJS_INFO) $(LIBS)
---
> 	$(CC) -g -o $@ $(OBJS_INFO) $(LDFLAGS) $(PACKAGE_LDFLAGS)
