Removes Strip during install

--- ppp-2.4.4/chat/Makefile.linux.old	2009-08-24 15:10:52.000000000 -0400
+++ ppp-2.4.4/chat/Makefile.linux	2009-08-24 15:11:01.000000000 -0400
@@ -25,7 +25,7 @@
 
 install: chat
 	mkdir -p $(BINDIR) $(MANDIR)
-	$(INSTALL) -s -c chat $(BINDIR)
+	$(INSTALL) -c chat $(BINDIR)
 	$(INSTALL) -c -m 644 chat.8 $(MANDIR)
 
 clean:
--- ppp-2.4.4/pppd/Makefile.linux.old	2009-08-24 15:12:01.000000000 -0400
+++ ppp-2.4.4/pppd/Makefile.linux	2009-08-24 15:13:03.000000000 -0400
@@ -99,7 +99,7 @@
 CFLAGS	+= -DUSE_SRP -DOPENSSL -I/usr/local/ssl/include
 LIBS	+= -lsrp -L/usr/local/ssl/lib -lcrypto
 TARGETS	+= srp-entry
-EXTRAINSTALL = $(INSTALL) -s -c -m 555 srp-entry $(BINDIR)/srp-entry
+EXTRAINSTALL = $(INSTALL) -c -m 555 srp-entry $(BINDIR)/srp-entry
 MANPAGES += srp-entry.8
 EXTRACLEAN += srp-entry.o
 NEEDDES=y
@@ -200,7 +200,7 @@
 install: pppd
 	mkdir -p $(BINDIR) $(MANDIR)
 	$(EXTRAINSTALL)
-	$(INSTALL) -s -c -m 555 pppd $(BINDIR)/pppd
+	$(INSTALL) -c -m 555 pppd $(BINDIR)/pppd
 	if chgrp pppusers $(BINDIR)/pppd 2>/dev/null; then \
 	  chmod o-rx,u+s $(BINDIR)/pppd; fi
 	$(INSTALL) -c -m 444 pppd.8 $(MANDIR)
--- ppp-2.4.4/pppdump/Makefile.linux.old	2009-08-24 15:14:06.000000000 -0400
+++ ppp-2.4.4/pppdump/Makefile.linux	2009-08-24 15:14:15.000000000 -0400
@@ -17,5 +17,5 @@
 
 install:
 	mkdir -p $(BINDIR) $(MANDIR)
-	$(INSTALL) -s -c pppdump $(BINDIR)
+	$(INSTALL) -c pppdump $(BINDIR)
 	$(INSTALL) -c -m 444 pppdump.8 $(MANDIR)
--- ppp-2.4.4/pppstats/Makefile.linux.old	2009-08-24 15:14:41.000000000 -0400
+++ ppp-2.4.4/pppstats/Makefile.linux	2009-08-24 15:14:47.000000000 -0400
@@ -22,7 +22,7 @@
 
 install: pppstats
 	-mkdir -p $(MANDIR)
-	$(INSTALL) -s -c pppstats $(BINDIR)
+	$(INSTALL) -c pppstats $(BINDIR)
 	$(INSTALL) -c -m 444 pppstats.8 $(MANDIR)
 
 pppstats: $(PPPSTATSRCS)
--- ppp-2.4.4/pppd/plugins/rp-pppoe/Makefile.linux.old	2009-08-24 15:16:03.000000000 -0400
+++ ppp-2.4.4/pppd/plugins/rp-pppoe/Makefile.linux	2009-08-24 15:16:18.000000000 -0400
@@ -39,9 +39,9 @@
 
 install: all
 	$(INSTALL) -d -m 755 $(LIBDIR)
-	$(INSTALL) -s -c -m 4550 rp-pppoe.so $(LIBDIR)
+	$(INSTALL) -c -m 4550 rp-pppoe.so $(LIBDIR)
 	$(INSTALL) -d -m 755 $(BINDIR)
-	$(INSTALL) -s -c -m 555 pppoe-discovery $(BINDIR)
+	$(INSTALL) -c -m 555 pppoe-discovery $(BINDIR)
 
 clean:
 	rm -f *.o *.so
--- ppp-2.4.4/pppd/plugins/radius/Makefile.linux.old	2009-08-24 15:16:41.000000000 -0400
+++ ppp-2.4.4/pppd/plugins/radius/Makefile.linux	2009-08-24 15:17:10.000000000 -0400
@@ -36,11 +36,11 @@
 
 install: all
 	$(INSTALL) -d -m 755 $(LIBDIR)
-	$(INSTALL) -s -c -m 755 radius.so $(LIBDIR)
-	$(INSTALL) -s -c -m 755 radattr.so $(LIBDIR)
-	$(INSTALL) -s -c -m 755 radrealms.so $(LIBDIR)
-	$(INSTALL) -c -m 444 pppd-radius.8 $(MANDIR)
-	$(INSTALL) -c -m 444 pppd-radattr.8 $(MANDIR)
+	$(INSTALL) -c -m 755 radius.so $(LIBDIR)
+	$(INSTALL) -c -m 755 radattr.so $(LIBDIR)
+	$(INSTALL) -c -m 755 radrealms.so $(LIBDIR)
+	$(INSTALL) -m 444 pppd-radius.8 $(MANDIR)
+	$(INSTALL) -m 444 pppd-radattr.8 $(MANDIR)
 
 radius.so: radius.o libradiusclient.a
 	$(CC) $(LDFLAGS) -o radius.so -shared radius.o libradiusclient.a
