DESCRIPTION = "Video Disk Recorder (VDR) is a digital sat-receiver program using Linux and DVB technologies. It allows one to record MPEG2 streams, as well as output the stream to TV. It is also possible to watch DVDs (hardware accelerated) with some comfort and use an IR remote control."
HOMEPAGE = "http://www.tvdr.de"
SECTION = "console/multimedia"
LICENSE = "GPLv2"
AUTHOR = "Klaus Schmidinger"
DEPENDS = "fontconfig freetype gettext libcap jpeg virtual/libintl"

SRC_URI = "ftp://ftp.tvdr.de/vdr/Developer/${P}.tar.bz2"
