PR = "r2"

IMAGE_LINGUAS = ""
USE_DEVFS = "1"

SWITCHBOX_BASE_DEPENDS = "switchbox"
SWITCHBOX_BASE_PACKAGES = "switchbox"

IMAGE_VARIANT = "switchbox"

IMAGE_BASENAME = "${IMAGE_VARIANT}"

IPKG_INSTALL = "${SWITCHBOX_BASE_PACKAGES}"

DEPENDS  = "${SWITCHBOX_BASE_DEPENDS}"

inherit image_ipk
LICENSE = MIT
