#!/bin/sh
#
# reboot	Execute the reboot command.
#

PATH=/sbin:/bin:/usr/sbin:/usr/bin

echo "Rebooting... "

if test -x /usr/sbin/kexec ; then
    echo " Trying kexec first..."
    /usr/sbin/kexec --force --exec #--no-ifdown
    echo " No kexec kernel loaded (or kexec failed), doing normal reboot..."
fi

reboot -d -f -i
