--- bt950-0.1/Makefile.orig	2002-11-17 04:39:14 +0100
+++ bt950-0.1/Makefile	2004-10-15 13:03:01 +0200
@@ -1,7 +1,7 @@
 INCLUDEDIR = /usr/src/linux/include
 
 CC = gcc
-CFLAGS = -D__KERNEL__ -I$(INCLUDEDIR) -I. -DMODULE -Wall -Wstrict-prototypes -O2
+CFLAGS = -D__KERNEL__ -I$(KERNEL_PATH)/include -I. -DMODULE -Wall -Wstrict-prototypes -O2
 
 
 all: bt950_cs.o
