#!/bin/sh
. /etc/init.d/functions

if [ "$(machine_id)" = "ti8168evm" ] ; then
	echo TI816x
else
	devmem2 0x4800244c | \
	grep 'Read at address' | \
	sed -e 's/.*): //' | \
	sed -e 's/0x00005C00/OMAP3503/' -e 's/0x00001C00/OMAP3515/' -e 's/0x00004C00/OMAP3525/' -e 's/0x00000C00/OMAP3530/'
fi
