#!/bin/sh
# . this file to load the functions for automatically loading modules
# NB: /proc must be mounted for correct evaluation of "$(machine)".

. /etc/default/functions

loaddiskmods(){
	case "$(machine)" in
	    nslu2)		       
		[ -d /sys/module/ehci_hcd ]   || modprobe ehci-hcd
		[ -d /sys/module/ohci_hcd ]   || modprobe ohci-hcd
		;;
	    nas100d)
		[ -d /sys/module/ehci_hcd ]   || modprobe ehci-hcd
		[ -d /sys/module/uhci_hcd ]   || modprobe uhci-hcd
		[ -d /sys/module/pata_artop ] || modprobe pata-artop
		;;
	    dsmg600)
		[ -d /sys/module/ehci_hcd ]   || modprobe ehci-hcd
		[ -d /sys/module/uhci_hcd ]   || modprobe uhci-hcd
		[ -d /sys/module/pata_artop ] || modprobe pata-artop
		;;

	esac
}

loadnetmods(){
	case "$(machine)" in
	    dsmg600)
		[ -d /sys/module/via_velocity ] || modprobe via-velocity
		;;
	    *)
		true
		;;
	esac
}

loadnfsmods(){
	[ -d /sys/module/nfs ] || modprobe nfs
}

loadmiscmods(){
	true
}

