#!/bin/sh
#
# Session script for fluxbox-gpe, heavily based on matchbox's session script
#

# Install "apps" file with defaults for GPE usage

MACHINE="`cat /proc/cpuinfo | sed -n "/^Hardware/s/.*\:\ \(.*\)/\1/p"`"

case $MACHINE in
*Akita | *Spitz | *Borzoi | *Terrier)	
	APPS="apps.gpe.akita"
	KEYS="keys.akita";;
*)	
	APPS="apps.gpe.default"
	KEYS="keys.default";;
esac

if test -e /usr/share/fluxbox/$APPS
then
	mkdir -p $HOME/.fluxbox
	test -e $HOME/.fluxbox/apps || cp /usr/share/fluxbox/$APPS $HOME/.fluxbox/apps
fi

if test -e /usr/share/fluxbox/$KEYS
then
	mkdir -p $HOME/.fluxbox
	test -e $HOME/.fluxbox/keys || cp /usr/share/fluxbox/$KEYS $HOME/.fluxbox/keys
fi


if [ -e $HOME/.fluxbox/session ]
then
exec $HOME/.fluxbox/session
fi

if [ -e /usr/share/fluxbox/session ]
then
exec /usr/share/fluxbox/session
fi

# Default files to run if $HOME/.matchbox/session or /etc/matchbox/session
# dont exist. 

matchbox-desktop &
matchbox-panel  --orientation south -no-flip &
sleep 5
exec startfluxbox $@  
