SECTION = "console/utils"
DESCRIPTION = "Console utilities for building the OpenSIMpad linux distribution"
HOMEPAGE = "http://opensimpad.org"
DEPENDS = "pad-native genboot-native serload-native"
MAINTAINER = "Michael 'Mickey' Lauer <mickey@Vanille.de>"
LICENSE = "MIT"