*** setpwc-0.9/Makefile.orig	2005-07-26 09:16:09.000000000 +0930
--- setpwc-0.9/Makefile	2005-07-26 09:16:18.000000000 +0930
***************
*** 22,30 ****
  
  setpwc: $(OBJS)
  	$(CC) -Wall -W $(OBJS) $(LDFLAGS) -o setpwc
- 	strip setpwc
- 	echo
- 	echo Oh, blatant plug: http://keetweej.vanheusden.com/wishlist.html
  
  install: setpwc
  	cp setpwc /usr/bin
--- 22,27 ----
