#! /bin/sh
#
# syslog	init.d script for busybox syslogd/klogd
#		Written by Robert Griebl <sandman@handhelds.org>
#

# log to remote host
# SYSLOG_ARGS="-R remote.host"

# log to 16K shm circular buffer
SYSLOG_ARGS="-C"

set -e

case "$1" in
  start)
	echo -n "Starting syslogd/klogd: "
	start-stop-daemon -S -b -n syslogd -a /sbin/syslogd -- -n $SYSLOG_ARGS
	start-stop-daemon -S -b -n klogd -a /sbin/klogd -- -n
	echo "done"
	;;
  stop)
	echo -n "Stopping syslogd/klogd: "
	start-stop-daemon -K -n syslogd
	start-stop-daemon -K -n klogd
	echo "done"
	;;
  *)
	echo "Usage: syslog {start|stop}" >&2
	exit 1
	;;
esac

exit 0
