
#
# Patch managed by http://www.holgerschurig.de/patcher.html
#

--- /dev/null
+++ ixp425-eth-1.1-r0/Makefile
@@ -0,0 +1,10 @@
+ifneq ($(KERNELRELEASE),)
+obj-m	:= ixp425_eth.o
+
+else
+KDIR	:= /lib/modules/$(shell uname -r)/build
+PWD	:= $(shell pwd)
+
+default modules:
+	$(MAKE) -C $(KDIR) SUBDIRS=$(PWD) modules
+endif
