# Codec engine needs a specific set of version of its dependencies, so we specify them here:
# - using edma-lld 01.11.00.03 (instead of 01.11.00.02) to fix installer issue.

PREFERRED_VERSION_ti-codec-engine = "2_25_01_06"
 
PREFERRED_VERSION_ti-biosutils = "1_02_02"
PREFERRED_VERSION_ti-cgt6x = "6_1_9"
PREFERRED_VERSION_ti-dspbios = "5_41_02_14"
PREFERRED_VERSION_ti-dsplink-module = "1_64"
PREFERRED_VERSION_ti-edma3lld = "01_11_00_03"
PREFERRED_VERSION_ti-framework-components = "2_25_01_05"
PREFERRED_VERSION_ti-linuxutils = "2_25_01_06"
PREFERRED_VERSION_ti-lpm-module = "1_24_01"
PREFERRED_VERSION_ti-xdais = "6_25_01_08"
PREFERRED_VERSION_ti-xdctools = "3_16_01_27"
