# Codec engine needs a specific set of version of its dependencies, so we specify them here:

PREFERRED_VERSION_ti-codec-engine = "2_25_00_05"
 
PREFERRED_VERSION_ti-biosutils = "1_02_02"
PREFERRED_VERSION_ti-cgt6x = "6_1_9"
PREFERRED_VERSION_ti-dspbios = "5_41_02_14"
PREFERRED_VERSION_ti-dsplink-module = "1_64"
PREFERRED_VERSION_ti-edma3lld = "01_11_00_02"
PREFERRED_VERSION_ti-framework-components = "2_25_00_04"
PREFERRED_VERSION_ti-linuxutils = "2_25_01_06"
PREFERRED_VERSION_ti-lpm-module = "2_24_01"
PREFERRED_VERSION_ti-xdais = "6_25_00_07"
PREFERRED_VERSION_ti-xdctools = "3_16_01_27"
