# Warning! Builds unupgradable packages!

# OpenMoko
SRCDATE_libgsmd ?= "now"
SRCDATE_libmokogsmd2 ?= "now"
SRCDATE_libmokoui2 ?= "now"
SRCDATE_libmokojournal2 ?= "now"
SRCDATE_libmokopanelui2 ?= "now"
SRCDATE_openmoko-today2 ?= "now"
SRCDATE_openmoko-dialer2 ?= "now"
SRCDATE_openmoko-contacts2 ?= "now"

SRCDATE_openmoko-panel-battery ?= "now"
SRCDATE_openmoko-panel-clock ?= "now"
SRCDATE_openmoko-panel-gsm ?= "now"
SRCDATE_openmoko-panel-usb ?= "now"
SRCDATE_openmoko-panel-bt ?= "now"
SRCDATE_openmoko-panel-gps ?= "now"
