# SHR autorev include
SRCREV_pn-e-wm-config-illume2-shr = "${AUTOREV}"
SRCREV_pn-shr-settings = "${AUTOREV}"
SRCREV_pn-shr-specs = "${AUTOREV}"
SRCREV_pn-phoneui-apps = "${AUTOREV}"
SRCREV_pn-phoneuid = "${AUTOREV}"
SRCREV_pn-phonefsod = "${AUTOREV}"
SRCREV_pn-libphone-ui = "${AUTOREV}"
SRCREV_pn-libphone-ui-shr = "${AUTOREV}"
SRCREV_pn-libphone-utils = "${AUTOREV}"
SRCREV_pn-opimd-utils = "${AUTOREV}"
SRCREV_pn-shr-installer = "${AUTOREV}"
SRCREV_pn-shr-wizard = "${AUTOREV}"

# mokosuite2 + deps
SRCREV_pn-mokosuite2 = "${AUTOREV}"
SRCREV_pn-mokowm = "${AUTOREV}"
SRCREV_pn-mokowm-imf-ecore = "${AUTOREV}"
