# SHR autorev include
SRCREV_pn-frameworkd-config-shr = "${AUTOREV}"
SRCREV_pn-frameworkd-config-shr_FSO_REV = "${AUTOREV}"
SRCREV_pn-frameworkd-config-shr_SHR_REV = "${AUTOREV}"

SRCREV_pn-alsa-scenarii-shr = "${AUTOREV}"
SRCREV_pn-shr-settings = "${AUTOREV}"
SRCREV_pn-shr-specs = "${AUTOREV}"
SRCREV_pn-phoneui-apps = "${AUTOREV}"
SRCREV_pn-phoneuid = "${AUTOREV}"
SRCREV_pn-phonefsod = "${AUTOREV}"
SRCREV_pn-libphone-ui = "${AUTOREV}"
SRCREV_pn-libphone-ui-shr = "${AUTOREV}"
SRCREV_pn-libphone-utils = "${AUTOREV}"
SRCREV_pn-opimd-utils = "${AUTOREV}"

