IMAGE_ROOTFS_SIZE_ext2 = "85000"
IMAGE_ROOTFS_SIZE_ext2.gz = "85000"
IMAGE_LINGUAS = ""

MYTHFRONT_PACKAGES = "${MACHINE_TASK_PROVIDER} task-mythfront"

DEPENDS = "${MYTHFRONT_PACKAGES}"
IMAGE_INSTALL = "${MYTHFRONT_PACKAGES}"

inherit image
