--- char-driver/Makefile.orig	2008-03-09 14:38:02.000000000 -0600
+++ char-driver/Makefile	2008-03-09 14:39:04.000000000 -0600
@@ -19,10 +19,10 @@
 
 PWD       := $(shell pwd)
 
-GUMSTIX_BUILDROOT	= $(PWD)/../gumstix-buildroot
-BUILD_ARM			= $(wildcard $(GUMSTIX_BUILDROOT)/build_arm*)
-KERNELDIR 		   ?= $(wildcard $(BUILD_ARM)/linux-*)
-CROSS_COMPILE		= $(BUILD_ARM)/staging_dir/bin/arm-linux-
+#GUMSTIX_BUILDROOT	= $(PWD)/../gumstix-buildroot
+#BUILD_ARM			= $(wildcard $(GUMSTIX_BUILDROOT)/build_arm*)
+#KERNELDIR 		   ?= $(wildcard $(BUILD_ARM)/linux-*)
+#CROSS_COMPILE		= $(BUILD_ARM)/staging_dir/bin/arm-linux-
 
 default: user-apps kernel-module
 
@@ -31,7 +31,7 @@
 user-apps: sample
 
 TARGET_ARCH=-Os -march=armv5te -mtune=xscale -Wa,-mcpu=xscale
-CC = $(CROSS_COMPILE)gcc
+#CC = $(CROSS_COMPILE)gcc
 
 sample: sample.c
 
