--- a/Makefile	2010-01-24 17:43:22.000000000 +0300
+++ b/Makefile	2010-04-20 12:33:33.000000000 +0400
@@ -66,7 +66,6 @@ endif
 ABI_FLAGS:=
 CFLAGS:=$(ABI_FLAGS) $(COPT_FLAGS) $(WARN_FLAGS) -Ikernel/include -I. # -g -DIPSET_DEBUG
 SH_CFLAGS:=$(CFLAGS) -fPIC
-LDFLAGS:=$(ABI_FLAGS)
 SETTYPES:=ipmap portmap macipmap
 SETTYPES+=iptree iptreemap
 SETTYPES+=iphash nethash ipporthash ipportiphash ipportnethash
