#! /bin/sh
matrixgui="/usr/bin/matrix_gui"
GUI_OPTS="-qws -geometry 720x480+0+10 -display transformed:Rot0 /usr/share/matrix/html/menu_main.html"

test -x "$matrixgui" || exit 0

case "$1" in
  start)
    # switch to component 480p mode
    echo 480P-60 > /sys/class/davinci_display/ch0/mode
    echo COMPONENT > /sys/class/davinci_display/ch0/output
    echo -n "Starting Matrix GUI application"
    start-stop-daemon --start --quiet --background --pidfile /var/run/matrix-gui.pid --exec $matrixgui -- $GUI_OPTS
    echo "."
    ;;
  stop)
    echo -n "Stopping Matrix GUI application"
    start-stop-daemon --stop --quiet --pidfile /var/run/matrix-gui.pid
    echo "."
    ;;
  *)
    echo "Usage: /etc/init.d/matrix-gui {start|stop}"
    exit 1
esac

exit 0
