#!/bin/sh

for x in $(cat /proc/cmdline); do
        case $x in
        dropbear=early)
                echo "Starting dropbear early"
                exec /etc/init.d/dropbear $*
                ;;
        esac
done
