#!/bin/sh

BROWSERDIR=""
BROWSERAPP="browser"

#Check if DISPLAY is set.  If so we assume we are running in X11
#and will call the X11 version of the browser if it exists.
if [ "$DISPLAY" == "" ]
then
    BROWSERDIR="/usr/bin/qtopia/demos/browser"
else
    BROWSERDIR="/usr/bin/qt4/demos/browser"
fi

if [ -e "$BROWSERDIR/$BROWSERAPP" ]
then
    cd $BROWSERDIR
    ./$BROWSERAPP
fi

