#!/bin/sh
ACTUALCONF=/var/run/resolv.conf
PPPCONF=/var/run/ppp/resolv.conf
if [ -x /sbin/resolvconf ] ; then
	cat $PPPCONF | resolvconf -a $PPP_IFACE
elif [ -f $PPPCONF ] ; then
	if [ -f $ACTUALCONF ] ; then
		if [ ! -h $ACTUALCONF -o ! "`readlink $ACTUALCONF 2>&1`" = "$PPPCONF" ] ; then
			mv $ACTUALCONF $ACTUALCONF.ppporig
		fi
	fi

	ln -sf $PPPCONF $ACTUALCONF
fi
