Index: squashfs-tools/Makefile
===================================================================
--- squashfs-tools.orig/Makefile	2006-08-21 01:42:45.000000000 +0200
+++ squashfs-tools/Makefile	2006-09-21 11:42:10.000000000 +0200
@@ -1,19 +1,24 @@
 INCLUDEDIR = .
 
 CFLAGS := -I$(INCLUDEDIR) -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -O2
+CFLAGS_R = -I$(INCLUDEDIR) -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE
+LIBS = -lz
 
 all: mksquashfs unsquashfs
 
 mksquashfs: mksquashfs.o read_fs.o sort.o
-	$(CC) mksquashfs.o read_fs.o sort.o -lz -lpthread -o $@
+	$(CC) $(LDFLAGS) mksquashfs.o read_fs.o sort.o -lz -lpthread -o $@
 
 mksquashfs.o: mksquashfs.c squashfs_fs.h mksquashfs.h global.h sort.h
+ 	$(CC) $(CFLAGS_R) $(CFLAGS) -c -o mksquashfs.o mksquashfs.c
 
 read_fs.o: read_fs.c squashfs_fs.h read_fs.h global.h
+ 	$(CC) $(CFLAGS_R) $(CFLAGS) -c -o read_fs.o read_fs.c
 
 sort.o: sort.c squashfs_fs.h global.h sort.h
+ 	$(CC) $(CFLAGS_R) $(CFLAGS) -c -o sort.o sort.c
 
 unsquashfs: unsquashfs.o
-	$(CC) unsquashfs.o -lz -o $@
+	$(CC) $(LDFLAGS) unsquashfs.o -lz -o $@
 
 unsquashfs.o: unsquashfs.c squashfs_fs.h read_fs.h global.h
