#
# Specify which versions of E-related libraries and applications to build
#

PREFERRED_VERSION_ecore = "0.9.9.007"
PREFERRED_VERSION_edb = "1.0.5.003"
PREFERRED_VERSION_edje = "0.5.0.007"
PREFERRED_VERSION_eet = "0.9.10.007"
PREFERRED_VERSION_embryo = "0.9.1.007"
PREFERRED_VERSION_etox = "0.9.0.003"
PREFERRED_VERSION_evas = "0.9.9.007"
PREFERRED_VERSION_ewl = "0.0.4.003"
PREFERRED_VERSION_imlib2 = "1.2.0.007"

