--- gpsdrive-2.10pre2-ipaq/Makefile	2007-11-11 13:29:10.000000000 +0300
+++ gpsdrive-2.10pre2-ipaq.patched/Makefile	2008-01-12 19:18:46.000000000 +0300
@@ -5,11 +5,11 @@
 STRIP = arm-linux-strip
 
 DEFS = -DLOCALEDIR=\"/usr/share/locale\" -DDATADIR=\"/usr/share\"
-INCLUDES = -I. -I/usr/include/gtk-2.0 -I/usr/lib/gtk-2.0/include -I/usr/include/glib-2.0/ -I/usr/lib/glib-2.0/include -I/usr/include/pango-1.0 -I/usr/include/atk-1.0 -I/usr/include/cairo
+INCLUDES = -I. `pkg-config gtk+-2.0 --cflags` 
 
 CFLAGS = -O2 -pipe
 
-LIBRARIES = -L/usr/lib -lcrypt -lpthread -lgtk-x11-2.0 -lgdk-x11-2.0 -latk-1.0 -lpango-1.0 -lgobject-2.0 -lgmodule-2.0 -lglib-2.0 -lm -lc
+LIBRARIES = -lcrypt -lpthread -lm -lc `pkg-config gtk+-2.0 --libs`
 LDFLAGS =
 
 SOURCES = gpsdrive.c speech_out.c track.c settings.c splash.c gpsserial.c gpsmisc.c \
