#!/bin/sh
# boot from the current (flash) root partition
# nothing need be done apart from setting the
# system LED status correctly
. /etc/default/functions
scc -l redflash -f auto
test -x /sbin/init && exec /sbin/init
# fallback if /sbin/init has been deleted (bad!)
scc -l red 
exec <>/dev/console >&0 2>&0
test -x /sbin/sulogin && exec /sbin/sulogin
test -x /bin/sh && exec /bin/sh
exit 1
