--- lua-5.1.3.orig/Makefile	2008-08-18 17:59:06.000000000 +0200
+++ lua-5.1.3/Makefile	2008-08-18 17:59:15.000000000 +0200
@@ -38,7 +38,7 @@
 # What to install.
 TO_BIN= lua luac
 TO_INC= lua.h luaconf.h lualib.h lauxlib.h ../etc/lua.hpp
-TO_LIB= liblua.a
+TO_LIB= liblua5.1.a
 TO_MAN= lua.1 luac.1
 
 # Lua version and release.
--- lua-5.1.3.orig/src/Makefile	2008-08-18 17:54:30.000000000 +0200
+++ lua-5.1.3/src/Makefile	2008-08-18 17:54:39.000000000 +0200
@@ -22,7 +22,7 @@
 
 PLATS= aix ansi bsd freebsd generic linux macosx mingw posix solaris
 
-LUA_A=	liblua.a
+LUA_A=	liblua5.1.a
 CORE_O=	lapi.o lcode.o ldebug.o ldo.o ldump.o lfunc.o lgc.o llex.o lmem.o \
 	lobject.o lopcodes.o lparser.o lstate.o lstring.o ltable.o ltm.o  \
 	lundump.o lvm.o lzio.o
