
#
# Patch managed by http://www.mn-logistik.de/unsupported/pxa250/patcher
#

--- comprec-0.01/Makefile~makefile	2003-01-21 16:29:20.000000000 -0500
+++ comprec-0.01/Makefile	2004-03-04 03:34:10.000000000 -0500
@@ -1,16 +1,17 @@
 ZROOT=/home/zaurus/develop
-CC_NATIVE=gcc
-CC=$(ZROOT)/arm/bin/arm-linux-gcc
-AS=$(ZROOT)/arm/bin/arm-v4l-linux-as
-STRIP=$(ZROOT)/arm/bin/arm-v4l-linux-strip
+BUILD_CC=gcc
+CC=$(BUILD_CC)
+AS=as	
+LD=ld
+STRIP=strip
 IPKG_BUILD=./ipkg-build
 
-CFLAGS+=-Wall -O2 -fno-exceptions -g
-LDFLAGS+=-lm -g
+CFLAGS=-Wall -O2 -fno-exceptions
+LDFLAGS=
+LIBS=-lm
 
 VERSION=0.01
 
-
 OBJECTS=bitstream.o huffman.o layer3.o loop.o main.o \
 	utils.o wave.o coder_sa.o coder.o
 CSOURCES=bitstream.c coder.c huffman.c layer3.c loop.c main.c \
@@ -21,14 +22,14 @@
 	README ipkg-build control.in
 
 shine: table1.h table2.h $(OBJECTS) 
-	$(CC) -o $@ $(OBJECTS) $(LDFLAGS)
+	$(CC) -o $@ $(LDFLAGS) $(LIBS) $(OBJECTS)
 	$(STRIP) $@
 
 table1.h table2.h: tables
-	tables
+	./tables
 
 tables: tables.c
-	$(CC_NATIVE) -o $@ $(CFLAGS) $< -lm
+	$(BUILD_CC) -o $@ $(CFLAGS) $< -lm
 
 clean:
 	rm -f $(OBJECTS) shine .depend
