/* File automatically generated by genmdesc, don't change */

const char * const arm_cpu_desc [OP_LAST] = {
	"\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x4" "",	/* nop */
	"\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x4" "",	/* break */
	"\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "",	/* ldarg.0 */
	"\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "",	/* ldarg.1 */
	"\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "",	/* ldarg.2 */
	"\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "",	/* ldarg.3 */
	"\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "",	/* ldloc.0 */
	"\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "",	/* ldloc.1 */
	"\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "",	/* ldloc.2 */
	"\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "",	/* ldloc.3 */
	"\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "",	/* stloc.0 */
	"\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "",	/* stloc.1 */
	"\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "",	/* stloc.2 */
	"\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "",	/* stloc.3 */
	"\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "",	/* ldarg.s */
	"\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "",	/* ldarga.s */
	"\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "",	/* starg.s */
	"\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "",	/* ldloc.s */
	"\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "",	/* ldloca.s */
	"\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "",	/* stloc.s */
	"\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "",	/* ldnull */
	"\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "",	/* ldc.i4.m1 */
	"\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "",	/* ldc.i4.0 */
	"\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "",	/* ldc.i4.1 */
	"\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "",	/* ldc.i4.2 */
	"\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "",	/* ldc.i4.3 */
	"\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "",	/* ldc.i4.4 */
	"\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "",	/* ldc.i4.5 */
	"\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "",	/* ldc.i4.6 */
	"\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "",	/* ldc.i4.7 */
	"\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "",	/* ldc.i4.8 */
	"\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "",	/* ldc.i4.s */
	"\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "",	/* ldc.i4 */
	"\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "",	/* ldc.i8 */
	"\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "",	/* ldc.r4 */
	"\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "",	/* ldc.r8 */
	NULL,	/* unused99 */
	"\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "",	/* dup */
	"\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "",	/* pop */
	"\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x5c" "",	/* jmp */
	"a\x0" "\x0" "\x0" "c\x0" "\x0" "\x0" "\x14" "",	/* call */
	"\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "",	/* calli */
	"\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "",	/* ret */
	"\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "",	/* br.s */
	"\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "",	/* brfalse.s */
	"\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "",	/* brtrue.s */
	"\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "",	/* beq.s */
	"\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "",	/* bge.s */
	"\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "",	/* bgt.s */
	"\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "",	/* ble.s */
	"\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "",	/* blt.s */
	"\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "",	/* bne.un.s */
	"\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "",	/* bge.un.s */
	"\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "",	/* bgt.un.s */
	"\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "",	/* ble.un.s */
	"\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "",	/* blt.un.s */
	"\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x4" "",	/* br */
	"\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "",	/* brfalse */
	"\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "",	/* brtrue */
	"\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x8" "",	/* beq */
	"\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x8" "",	/* bge */
	"\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x8" "",	/* bgt */
	"\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x8" "",	/* ble */
	"\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x8" "",	/* blt */
	"\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x8" "",	/* bne.un */
	"\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x8" "",	/* bge.un */
	"\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x8" "",	/* bgt.un */
	"\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x8" "",	/* ble.un */
	"\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x8" "",	/* blt.un */
	"\x0" "i\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x8" "",	/* switch */
	"i\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x8" "",	/* ldind.i1 */
	"i\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x8" "",	/* ldind.u1 */
	"i\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x8" "",	/* ldind.i2 */
	"i\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x8" "",	/* ldind.u2 */
	"i\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x8" "",	/* ldind.i4 */
	"i\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x8" "",	/* ldind.u4 */
	"\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "",	/* ldind.i8 */
	"i\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x8" "",	/* ldind.i */
	"\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "",	/* ldind.r4 */
	"\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "",	/* ldind.r8 */
	"i\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x8" "",	/* ldind.ref */
	"\x0" "bi\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "",	/* stind.ref */
	"\x0" "bi\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "",	/* stind.i1 */
	"\x0" "bi\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "",	/* stind.i2 */
	"\x0" "bi\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "",	/* stind.i4 */
	"\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "",	/* stind.i8 */
	"\x0" "bf\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "",	/* stind.r4 */
	"\x0" "bf\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "",	/* stind.r8 */
	"iii\x0" "\x0" "\x0" "\x0" "\x0" "\x4" "",	/* add */
	"iii\x0" "\x0" "\x0" "\x0" "\x0" "\x4" "",	/* sub */
	"iii\x0" "\x0" "\x0" "\x0" "\x0" "\x4" "",	/* mul */
	"iii\x0" "\x0" "\x0" "\x0" "\x0" "\x28" "",	/* div */
	"iii\x0" "\x0" "\x0" "\x0" "\x0" "\x10" "",	/* div.un */
	"iii\x0" "\x0" "\x0" "\x0" "\x0" "0",	/* rem */
	"iii\x0" "\x0" "\x0" "\x0" "\x0" "\x18" "",	/* rem.un */
	"iii\x0" "\x0" "\x0" "\x0" "\x0" "\x4" "",	/* and */
	"iii\x0" "\x0" "\x0" "\x0" "\x0" "\x4" "",	/* or */
	"iii\x0" "\x0" "\x0" "\x0" "\x0" "\x4" "",	/* xor */
	"iii\x0" "\x0" "\x0" "\x0" "\x0" "\x4" "",	/* shl */
	"iii\x0" "\x0" "\x0" "\x0" "\x0" "\x4" "",	/* shr */
	"iii\x0" "\x0" "\x0" "\x0" "\x0" "\x4" "",	/* shr.un */
	"ii\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x4" "",	/* neg */
	"ii\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x4" "",	/* not */
	"ii\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x8" "",	/* conv.i1 */
	"ii\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x8" "",	/* conv.i2 */
	"ii\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x4" "",	/* conv.i4 */
	"\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "",	/* conv.i8 */
	"fi\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x24" "",	/* conv.r4 */
	"fi\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x24" "",	/* conv.r8 */
	"ii\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "",	/* conv.u4 */
	"\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "",	/* conv.u8 */
	"\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "",	/* callvirt */
	"\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "",	/* cpobj */
	"\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "",	/* ldobj */
	"\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "",	/* ldstr */
	"\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "",	/* newobj */
	"\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "",	/* castclass */
	"\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "",	/* isinst */
	"fi\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "8",	/* conv.r.un */
	NULL,	/* unused58 */
	NULL,	/* unused1 */
	"\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "",	/* unbox */
	"\x0" "i\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x14" "",	/* throw */
	"\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "",	/* ldfld */
	"\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "",	/* ldflda */
	"\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "",	/* stfld */
	"\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "",	/* ldsfld */
	"\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "",	/* ldsflda */
	"\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "",	/* stsfld */
	"\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "",	/* stobj */
	"\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "",	/* conv.ovf.i1.un */
	"\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "",	/* conv.ovf.i2.un */
	"\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "",	/* conv.ovf.i4.un */
	"\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "",	/* conv.ovf.i8.un */
	"\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "",	/* conv.ovf.u1.un */
	"\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "",	/* conv.ovf.u2.un */
	"\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "",	/* conv.ovf.u4.un */
	"\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "",	/* conv.ovf.u8.un */
	"\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "",	/* conv.ovf.i.un */
	"\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "",	/* conv.ovf.u.un */
	"\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "",	/* box */
	"\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "",	/* newarr */
	"\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "",	/* ldlen */
	"\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "",	/* ldelema */
	"\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "",	/* ldelem.i1 */
	"\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "",	/* ldelem.u1 */
	"\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "",	/* ldelem.i2 */
	"\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "",	/* ldelem.u2 */
	"\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "",	/* ldelem.i4 */
	"\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "",	/* ldelem.u4 */
	"\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "",	/* ldelem.i8 */
	"\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "",	/* ldelem.i */
	"\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "",	/* ldelem.r4 */
	"\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "",	/* ldelem.r8 */
	"\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "",	/* ldelem.ref */
	"\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "",	/* stelem.i */
	"\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "",	/* stelem.i1 */
	"\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "",	/* stelem.i2 */
	"\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "",	/* stelem.i4 */
	"\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "",	/* stelem.i8 */
	"\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "",	/* stelem.r4 */
	"\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "",	/* stelem.r8 */
	"\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "",	/* stelem.ref */
	NULL,	/* ldelem.any */
	NULL,	/* stelem.any */
	NULL,	/* unbox.any */
	NULL,	/* unused5 */
	NULL,	/* unused6 */
	NULL,	/* unused7 */
	NULL,	/* unused8 */
	NULL,	/* unused9 */
	NULL,	/* unused10 */
	NULL,	/* unused11 */
	NULL,	/* unused12 */
	NULL,	/* unused13 */
	NULL,	/* unused14 */
	NULL,	/* unused15 */
	NULL,	/* unused16 */
	NULL,	/* unused17 */
	"\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "",	/* conv.ovf.i1 */
	"\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "",	/* conv.ovf.u1 */
	"\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "",	/* conv.ovf.i2 */
	"\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "",	/* conv.ovf.u2 */
	"\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "",	/* conv.ovf.i4 */
	"\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "",	/* conv.ovf.u4 */
	"\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "",	/* conv.ovf.i8 */
	"\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "",	/* conv.ovf.u8 */
	NULL,	/* unused50 */
	NULL,	/* unused18 */
	NULL,	/* unused19 */
	NULL,	/* unused20 */
	NULL,	/* unused21 */
	NULL,	/* unused22 */
	NULL,	/* unused23 */
	"\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "",	/* refanyval */
	"ff\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x18" "",	/* ckfinite */
	NULL,	/* unused24 */
	NULL,	/* unused25 */
	"\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "",	/* mkrefany */
	NULL,	/* unused59 */
	NULL,	/* unused60 */
	NULL,	/* unused61 */
	NULL,	/* unused62 */
	NULL,	/* unused63 */
	NULL,	/* unused64 */
	NULL,	/* unused65 */
	NULL,	/* unused66 */
	NULL,	/* unused67 */
	"\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "",	/* ldtoken */
	"ii\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x8" "",	/* conv.u2 */
	"ii\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x4" "",	/* conv.u1 */
	"ii\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x4" "",	/* conv.i */
	"\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "",	/* conv.ovf.i */
	"\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "",	/* conv.ovf.u */
	"iii\x0" "\x0" "\x0" "\x0" "\x0" "\x10" "",	/* add.ovf */
	"iii\x0" "\x0" "\x0" "\x0" "\x0" "\x10" "",	/* add.ovf.un */
	"iii\x0" "\x0" "\x0" "\x0" "\x0" "\x10" "",	/* mul.ovf */
	"iii\x0" "\x0" "\x0" "\x0" "\x0" "\x10" "",	/* mul.ovf.un */
	"iii\x0" "\x0" "\x0" "\x0" "\x0" "\x10" "",	/* sub.ovf */
	"iii\x0" "\x0" "\x0" "\x0" "\x0" "\x10" "",	/* sub.ovf.un */
	"\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x14" "",	/* endfinally */
	"\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "",	/* leave */
	"\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "",	/* leave.s */
	"\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "",	/* stind.i */
	"ii\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x4" "",	/* conv.u */
	NULL,	/* unused26 */
	NULL,	/* unused27 */
	NULL,	/* unused28 */
	NULL,	/* unused29 */
	NULL,	/* unused30 */
	NULL,	/* unused31 */
	NULL,	/* unused32 */
	NULL,	/* unused33 */
	NULL,	/* unused34 */
	NULL,	/* unused35 */
	NULL,	/* unused36 */
	NULL,	/* unused37 */
	NULL,	/* unused38 */
	NULL,	/* unused39 */
	NULL,	/* unused40 */
	NULL,	/* unused41 */
	NULL,	/* unused42 */
	NULL,	/* unused43 */
	NULL,	/* unused44 */
	NULL,	/* unused45 */
	NULL,	/* unused46 */
	NULL,	/* unused47 */
	NULL,	/* unused48 */
	"\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "",	/* prefix7 */
	"\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "",	/* prefix6 */
	"\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "",	/* prefix5 */
	"\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "",	/* prefix4 */
	"\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "",	/* prefix3 */
	"\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "",	/* prefix2 */
	"\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "",	/* prefix1 */
	"\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "",	/* prefixref */
	"\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "",	/* arglist */
	"i\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\xc" "",	/* ceq */
	"i\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\xc" "",	/* cgt */
	"i\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\xc" "",	/* cgt.un */
	"i\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\xc" "",	/* clt */
	"i\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\xc" "",	/* clt.un */
	"\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "",	/* ldftn */
	"\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "",	/* ldvirtftn */
	NULL,	/* unused56 */
	"\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "",	/* ldarg */
	"\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "",	/* ldarga */
	"\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "",	/* starg */
	"\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "",	/* ldloc */
	"\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "",	/* ldloca */
	"\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "",	/* stloc */
	"ii\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x3c" "",	/* localloc */
	NULL,	/* unused57 */
	"\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x14" "",	/* endfilter */
	"\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "",	/* unaligned. */
	"\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "",	/* volatile. */
	"\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "",	/* tail. */
	"\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "",	/* initobj */
	NULL,	/* constrained. */
	"\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "",	/* cpblk */
	"\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "",	/* initblk */
	NULL,	/* no. */
	"\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "",	/* rethrow */
	NULL,	/* unused */
	"\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "",	/* sizeof */
	NULL,	/* refanytype */
	NULL,	/* readonly. */
	NULL,	/* unused53 */
	NULL,	/* unused54 */
	NULL,	/* unused55 */
	NULL,	/* unused70 */
	"\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "",	/* illegal */
	"\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "",	/* endmac */
	NULL,	/* mono_icall */
	"\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "",	/* mono_objaddr */
	"\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "",	/* mono_ldptr */
	"\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "",	/* mono_vtaddr */
	"\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "",	/* mono_newobj */
	"\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "",	/* mono_retobj */
	NULL,	/* mono_ldnativeobj */
	NULL,	/* mono_cisinst */
	NULL,	/* mono_ccastclass */
	NULL,	/* mono_save_lmf */
	NULL,	/* mono_restore_lmf */
	NULL,	/* mono_classconst */
	NULL,	/* mono_not_taken */
	"\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "",	/* load */
	"\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "",	/* ldaddr */
	"\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "",	/* store */
	NULL,	/* objaddr */
	NULL,	/* vtaddr */
	"\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "",	/* phi */
	"\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "",	/* rename */
	"\x0" "ii\x0" "\x0" "\x0" "\x0" "\x0" "\x4" "",	/* compare */
	"\x0" "i\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\xc" "",	/* compare_imm */
	"\x0" "ff\x0" "\x0" "\x0" "\x0" "\x0" "\xc" "",	/* fcompare */
	"\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "",	/* lcompare */
	NULL,	/* icompare */
	NULL,	/* icompare_imm */
	"\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "",	/* local */
	"\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "",	/* arg */
	"\x0" "i\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\xc" "",	/* oparglist */
	"\x0" "i\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x1" "",	/* outarg */
	NULL,	/* outarg_reg */
	NULL,	/* outarg_freg */
	"\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x10" "",	/* outarg_imm */
	NULL,	/* outarg_r4 */
	NULL,	/* outarg_r8 */
	NULL,	/* outarg_vt */
	NULL,	/* outarg_membase */
	NULL,	/* inarg_vt */
	"\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "",	/* retarg */
	"ai\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x4" "",	/* setret */
	NULL,	/* setfret */
	"\x0" "ii\x0" "\x0" "\x0" "\x0" "\x0" "\xc" "",	/* setlret */
	"ii\x0" "\x0" "r\x0" "\x0" "\x0" "\x4" "",	/* setreg */
	"i\x0" "\x0" "\x0" "r\x0" "\x0" "\x0" "\x10" "",	/* setregimm */
	"ff\x0" "\x0" "r\x0" "\x0" "\x0" "\x4" "",	/* setfreg */
	"\x0" "b\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x4" "",	/* checkthis */
	"\x0" "\x0" "\x0" "\x0" "c\x0" "\x0" "\x0" "\x14" "",	/* voidcall */
	NULL,	/* voidcallvirt */
	"\x0" "i\x0" "\x0" "c\x0" "\x0" "\x0" "\x8" "",	/* voidcall_reg */
	"\x0" "b\x0" "\x0" "c\x0" "\x0" "\x0" "\xc" "",	/* voidcall_membase */
	"g\x0" "\x0" "\x0" "c\x0" "\x0" "\x0" "\x14" "",	/* fcall */
	NULL,	/* fcallvirt */
	"gi\x0" "\x0" "c\x0" "\x0" "\x0" "\x8" "",	/* fcall_reg */
	"gb\x0" "\x0" "c\x0" "\x0" "\x0" "\xc" "",	/* fcall_membase */
	"l\x0" "\x0" "\x0" "c\x0" "\x0" "\x0" "\x14" "",	/* lcall */
	NULL,	/* lcallvirt */
	"li\x0" "\x0" "c\x0" "\x0" "\x0" "\x8" "",	/* lcall_reg */
	"lb\x0" "\x0" "c\x0" "\x0" "\x0" "\xc" "",	/* lcall_membase */
	"\x0" "\x0" "\x0" "\x0" "c\x0" "\x0" "\x0" "\x14" "",	/* vcall */
	NULL,	/* vcallvirt */
	"\x0" "i\x0" "\x0" "c\x0" "\x0" "\x0" "\x8" "",	/* vcall_reg */
	"\x0" "b\x0" "\x0" "c\x0" "\x0" "\x0" "\xc" "",	/* vcall_membase */
	"ai\x0" "\x0" "c\x0" "\x0" "\x0" "\x8" "",	/* call_reg */
	"ab\x0" "\x0" "c\x0" "\x0" "\x0" "\xc" "",	/* call_membase */
	"\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "",	/* trap */
	"i\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x10" "",	/* iconst */
	"\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "",	/* i8const */
	"f\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x14" "",	/* r4const */
	"f\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x14" "",	/* r8const */
	"\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "",	/* regvar */
	"\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "",	/* reg */
	"\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "",	/* regoffset */
	"\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "",	/* label */
	NULL,	/* check_array_type */
	NULL,	/* array_rank */
	NULL,	/* throw_or_null */
	"\x0" "i\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x14" "",	/* op_rethrow */
	"\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "",	/* refanytype */
	NULL,	/* op_newobj */
	"b\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x14" "",	/* store_membase_imm */
	"bi\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x14" "",	/* store_membase_reg */
	"b\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x14" "",	/* storei1_membase_imm */
	"bi\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\xc" "",	/* storei1_membase_reg */
	"b\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x14" "",	/* storei2_membase_imm */
	"bi\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\xc" "",	/* storei2_membase_reg */
	"b\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x14" "",	/* storei4_membase_imm */
	"bi\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x14" "",	/* storei4_membase_reg */
	"b\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "",	/* storei8_membase_imm */
	"bi\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "",	/* storei8_membase_reg */
	"bf\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\xc" "",	/* storer4_membase_reg */
	"bf\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\xc" "",	/* storer8_membase_reg */
	"ib\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x14" "",	/* load_membase */
	"ib\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x4" "",	/* loadi1_membase */
	"ib\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x4" "",	/* loadu1_membase */
	"ib\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x4" "",	/* loadi2_membase */
	"ib\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x4" "",	/* loadu2_membase */
	"ib\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x4" "",	/* loadi4_membase */
	"ib\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x4" "",	/* loadu4_membase */
	"ib\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "",	/* loadi8_membase */
	"fb\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x4" "",	/* loadr4_membase */
	"fb\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x4" "",	/* loadr8_membase */
	"ibi\x0" "\x0" "\x0" "\x0" "\x0" "\x4" "",	/* load_memindex */
	"ibi\x0" "\x0" "\x0" "\x0" "\x0" "\x4" "",	/* loadi1_memindex */
	"ibi\x0" "\x0" "\x0" "\x0" "\x0" "\x4" "",	/* loadu1_memindex */
	"ibi\x0" "\x0" "\x0" "\x0" "\x0" "\x4" "",	/* loadi2_memindex */
	"ibi\x0" "\x0" "\x0" "\x0" "\x0" "\x4" "",	/* loadu2_memindex */
	"ibi\x0" "\x0" "\x0" "\x0" "\x0" "\x4" "",	/* loadi4_memindex */
	"ibi\x0" "\x0" "\x0" "\x0" "\x0" "\x4" "",	/* loadu4_memindex */
	NULL,	/* loadi8_memindex */
	NULL,	/* loadr4_memindex */
	NULL,	/* loadr8_memindex */
	"bii\x0" "\x0" "\x0" "\x0" "\x0" "\x4" "",	/* store_memindex */
	"bii\x0" "\x0" "\x0" "\x0" "\x0" "\x4" "",	/* storei1_memindex */
	"bii\x0" "\x0" "\x0" "\x0" "\x0" "\x4" "",	/* storei2_memindex */
	"bii\x0" "\x0" "\x0" "\x0" "\x0" "\x4" "",	/* storei4_memindex */
	NULL,	/* storei8_memindex */
	NULL,	/* storer4_memindex */
	NULL,	/* storer8_memindex */
	NULL,	/* loadr8_spill_membase */
	"i\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x8" "",	/* loadu4_mem */
	"ii\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x4" "",	/* move */
	"ff\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x4" "",	/* fmove */
	"ii\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\xc" "",	/* add_imm */
	"ii\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\xc" "",	/* sub_imm */
	"ii\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\xc" "",	/* mul_imm */
	"iii\x0" "\x0" "\x0" "\x0" "\x0" "\x14" "",	/* div_imm */
	"iii\x0" "\x0" "\x0" "\x0" "\x0" "\xc" "",	/* div_un_imm */
	"iii\x0" "\x0" "\x0" "\x0" "\x0" "\x1c" "",	/* rem_imm */
	"iii\x0" "\x0" "\x0" "\x0" "\x0" "\x10" "",	/* rem_un_imm */
	"ii\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\xc" "",	/* and_imm */
	"ii\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\xc" "",	/* or_imm */
	"ii\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\xc" "",	/* xor_imm */
	"ii\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x8" "",	/* shl_imm */
	"ii\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x8" "",	/* shr_imm */
	"ii\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x8" "",	/* shr_un_imm */
	"\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x8" "",	/* cond_exc_eq */
	"\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x8" "",	/* cond_exc_ge */
	"\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x8" "",	/* cond_exc_gt */
	"\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x8" "",	/* cond_exc_le */
	"\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x8" "",	/* cond_exc_lt */
	"\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x8" "",	/* cond_exc_ne_un */
	"\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x8" "",	/* cond_exc_ge_un */
	"\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x8" "",	/* cond_exc_gt_un */
	"\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x8" "",	/* cond_exc_le_un */
	"\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x8" "",	/* cond_exc_lt_un */
	"\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\xc" "",	/* cond_exc_ov */
	"\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x8" "",	/* cond_exc_no */
	"\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\xc" "",	/* cond_exc_c */
	"\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x8" "",	/* cond_exc_nc */
	NULL,	/* cond_exc_ieq */
	NULL,	/* cond_exc_ige */
	NULL,	/* cond_exc_igt */
	NULL,	/* cond_exc_ile */
	NULL,	/* cond_exc_ilt */
	NULL,	/* cond_exc_ine_un */
	NULL,	/* cond_exc_ige_un */
	NULL,	/* cond_exc_igt_un */
	NULL,	/* cond_exc_ile_un */
	NULL,	/* cond_exc_ilt_un */
	NULL,	/* cond_exc_iov */
	NULL,	/* cond_exc_ino */
	NULL,	/* cond_exc_ic */
	NULL,	/* cond_exc_inc */
	"\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "",	/* long_add */
	"\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "",	/* long_sub */
	"\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "",	/* long_mul */
	"\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "",	/* long_div */
	"\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "",	/* long_div_un */
	"\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "",	/* long_rem */
	"\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "",	/* long_rem_un */
	"\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "",	/* long_and */
	"\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "",	/* long_or */
	"\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "",	/* long_xor */
	"\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "",	/* long_shl */
	"\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "",	/* long_shr */
	"\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "",	/* long_shr_un */
	"\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "",	/* long_neg */
	"\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "",	/* long_not */
	"\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "",	/* long_conv_to_i1 */
	"\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "",	/* long_conv_to_i2 */
	"\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "",	/* long_conv_to_i4 */
	"\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "",	/* long_conv_to_i8 */
	"\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "",	/* long_conv_to_r4 */
	"\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "",	/* long_conv_to_r8 */
	"\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "",	/* long_conv_to_u4 */
	"\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "",	/* long_conv_to_u8 */
	"\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "",	/* long_conv_to_u2 */
	"\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "",	/* long_conv_to_u1 */
	"\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "",	/* long_conv_to_i */
	"iii\x0" "\x0" "\x0" "\x0" "\x0" "\x1e" "",	/* long_conv_to_ovf_i */
	"\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "",	/* long_conv_to_ovf_u */
	"\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "",	/* long_add_ovf */
	"\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "",	/* long_add_ovf_un */
	"\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "",	/* long_mul_ovf */
	"\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "",	/* long_mul_ovf_un */
	"\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "",	/* long_sub_ovf */
	"\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "",	/* long_sub_ovf_un */
	"\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "",	/* long_conv_to_ovf_i1_un */
	"\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "",	/* long_conv_to_ovf_i2_un */
	"\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "",	/* long_conv_to_ovf_i4_un */
	"\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "",	/* long_conv_to_ovf_i8_un */
	"\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "",	/* long_conv_to_ovf_u1_un */
	"\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "",	/* long_conv_to_ovf_u2_un */
	"\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "",	/* long_conv_to_ovf_u4_un */
	"\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "",	/* long_conv_to_ovf_u8_un */
	"\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "",	/* long_conv_to_ovf_i_un */
	"\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "",	/* long_conv_to_ovf_u_un */
	"\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "",	/* long_conv_to_ovf_i1 */
	"\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "",	/* long_conv_to_ovf_u1 */
	"\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "",	/* long_conv_to_ovf_i2 */
	"\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "",	/* long_conv_to_ovf_u2 */
	"\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "",	/* long_conv_to_ovf_i4 */
	"\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "",	/* long_conv_to_ovf_u4 */
	"\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "",	/* long_conv_to_ovf_i8 */
	"\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "",	/* long_conv_to_ovf_u8 */
	"\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "",	/* long_ceq */
	"\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "",	/* long_cgt */
	"\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "",	/* long_cgt_un */
	"\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "",	/* long_clt */
	"\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "",	/* long_clt_un */
	"fii\x0" "\x0" "\x0" "\x0" "\x0" "\x25" "",	/* long_conv_to_r_un */
	"\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "",	/* long_conv_to_u */
	"\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "",	/* long_shr_imm */
	"\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "",	/* long_shr_un_imm */
	"\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "",	/* long_shl_imm */
	"\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "",	/* long_add_imm */
	"\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "",	/* long_sub_imm */
	NULL,	/* long_mul_imm */
	"\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "",	/* long_beq */
	"\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "",	/* long_bne_un */
	"\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "",	/* long_blt */
	"\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "",	/* long_blt_un */
	"\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "",	/* long_bgt */
	"\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "",	/* long_btg_un */
	"\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "",	/* long_bge */
	"\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "",	/* long_bge_un */
	"\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "",	/* long_ble */
	"\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "",	/* long_ble_un */
	NULL,	/* long_shr_un_32 */
	NULL,	/* int_add */
	NULL,	/* int_sub */
	NULL,	/* int_mul */
	NULL,	/* int_div */
	NULL,	/* int_div_un */
	NULL,	/* int_rem */
	NULL,	/* int_rem_un */
	NULL,	/* int_and */
	NULL,	/* int_or */
	NULL,	/* int_xor */
	NULL,	/* int_shl */
	NULL,	/* int_shr */
	NULL,	/* int_shr_un */
	NULL,	/* int_neg */
	NULL,	/* int_not */
	NULL,	/* int_conv_to_i1 */
	NULL,	/* int_conv_to_i2 */
	NULL,	/* int_conv_to_i4 */
	NULL,	/* int_conv_to_i8 */
	NULL,	/* int_conv_to_r4 */
	NULL,	/* int_conv_to_r8 */
	NULL,	/* int_conv_to_u4 */
	NULL,	/* int_conv_to_u8 */
	NULL,	/* int_conv_to_u2 */
	NULL,	/* int_conv_to_u1 */
	NULL,	/* int_conv_to_i */
	NULL,	/* int_conv_to_ovf_i */
	NULL,	/* int_conv_to_ovf_u */
	NULL,	/* int_add_ovf */
	NULL,	/* int_add_ovf_un */
	NULL,	/* int_mul_ovf */
	NULL,	/* int_mul_ovf_un */
	NULL,	/* int_sub_ovf */
	NULL,	/* int_sub_ovf_un */
	NULL,	/* int_conv_to_ovf_i1_un */
	NULL,	/* int_conv_to_ovf_i2_un */
	NULL,	/* int_conv_to_ovf_i4_un */
	NULL,	/* int_conv_to_ovf_i8_un */
	NULL,	/* int_conv_to_ovf_u1_un */
	NULL,	/* int_conv_to_ovf_u2_un */
	NULL,	/* int_conv_to_ovf_u4_un */
	NULL,	/* int_conv_to_ovf_u8_un */
	NULL,	/* int_conv_to_ovf_i_un */
	NULL,	/* int_conv_to_ovf_u_un */
	NULL,	/* int_conv_to_ovf_i1 */
	NULL,	/* int_conv_to_ovf_u1 */
	NULL,	/* int_conv_to_ovf_i2 */
	NULL,	/* int_conv_to_ovf_u2 */
	NULL,	/* int_conv_to_ovf_i4 */
	NULL,	/* int_conv_to_ovf_u4 */
	NULL,	/* int_conv_to_ovf_i8 */
	NULL,	/* int_conv_to_ovf_u8 */
	NULL,	/* int_adc */
	NULL,	/* int_adc_imm */
	NULL,	/* int_sbb */
	NULL,	/* int_sbb_imm */
	NULL,	/* int_addcc */
	NULL,	/* int_subcc */
	NULL,	/* int_add_imm */
	NULL,	/* int_sub_imm */
	NULL,	/* int_mul_imm */
	NULL,	/* int_div_imm */
	NULL,	/* int_div_un_imm */
	NULL,	/* int_rem_imm */
	NULL,	/* int_rem_un_imm */
	NULL,	/* int_and_imm */
	NULL,	/* int_or_imm */
	NULL,	/* int_xor_imm */
	NULL,	/* int_shl_imm */
	NULL,	/* int_shr_imm */
	NULL,	/* int_shr_un_imm */
	NULL,	/* int_ceq */
	NULL,	/* int_cgt */
	NULL,	/* int_cgt_un */
	NULL,	/* int_clt */
	NULL,	/* int_clt_un */
	NULL,	/* int_beq */
	NULL,	/* int_bne_un */
	NULL,	/* int_blt */
	NULL,	/* int_blt_un */
	NULL,	/* int_bgt */
	NULL,	/* int_bgt_un */
	NULL,	/* int_bge */
	NULL,	/* int_bge_un */
	NULL,	/* int_ble */
	NULL,	/* int_ble_un */
	"\x0" "ff\x0" "\x0" "\x0" "\x0" "\x0" "\x14" "",	/* float_beq */
	"\x0" "ff\x0" "\x0" "\x0" "\x0" "\x0" "\x14" "",	/* float_bne_un */
	"\x0" "ff\x0" "\x0" "\x0" "\x0" "\x0" "\x14" "",	/* float_blt */
	"\x0" "ff\x0" "\x0" "\x0" "\x0" "\x0" "\x14" "",	/* float_blt_un */
	"\x0" "ff\x0" "\x0" "\x0" "\x0" "\x0" "\x14" "",	/* float_bgt */
	"\x0" "ff\x0" "\x0" "\x0" "\x0" "\x0" "\x14" "",	/* float_btg_un */
	"\x0" "ff\x0" "\x0" "\x0" "\x0" "\x0" "\x14" "",	/* float_bge */
	"\x0" "ff\x0" "\x0" "\x0" "\x0" "\x0" "\x14" "",	/* float_bge_un */
	"\x0" "ff\x0" "\x0" "\x0" "\x0" "\x0" "\x14" "",	/* float_ble */
	"\x0" "ff\x0" "\x0" "\x0" "\x0" "\x0" "\x14" "",	/* float_ble_un */
	"fff\x0" "\x0" "\x0" "\x0" "\x0" "\x4" "",	/* float_add */
	"fff\x0" "\x0" "\x0" "\x0" "\x0" "\x4" "",	/* float_sub */
	"fff\x0" "\x0" "\x0" "\x0" "\x0" "\x4" "",	/* float_mul */
	"fff\x0" "\x0" "\x0" "\x0" "\x0" "\x4" "",	/* float_div */
	"fff\x0" "\x0" "\x0" "\x0" "\x0" "\x4" "",	/* float_div_un */
	"fff\x0" "\x0" "\x0" "\x0" "\x0" "\x10" "",	/* float_rem */
	"fff\x0" "\x0" "\x0" "\x0" "\x0" "\x10" "",	/* float_rem_un */
	"ff\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x4" "",	/* float_neg */
	"ff\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x4" "",	/* float_not */
	"if\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x28" "",	/* float_conv_to_i1 */
	"if\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x28" "",	/* float_conv_to_i2 */
	"if\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x28" "",	/* float_conv_to_i4 */
	"lf\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x28" "",	/* float_conv_to_i8 */
	"ff\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x4" "",	/* float_conv_to_r4 */
	"\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "",	/* float_conv_to_r8 */
	"if\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x28" "",	/* float_conv_to_u4 */
	"lf\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x28" "",	/* float_conv_to_u8 */
	"if\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x28" "",	/* float_conv_to_u2 */
	"if\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x28" "",	/* float_conv_to_u1 */
	"if\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x28" "",	/* float_conv_to_i */
	"\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "",	/* float_conv_to_ovf_i */
	"\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "",	/* float_conv_to_ovd_u */
	"\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "",	/* float_add_ovf */
	"\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "",	/* float_add_ovf_un */
	"\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "",	/* float_mul_ovf */
	"\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "",	/* float_mul_ovf_un */
	"\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "",	/* float_sub_ovf */
	"\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "",	/* float_sub_ovf_un */
	"\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "",	/* float_conv_to_ovf_i1_un */
	"\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "",	/* float_conv_to_ovf_i2_un */
	"\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "",	/* float_conv_to_ovf_i4_un */
	"\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "",	/* float_conv_to_ovf_i8_un */
	"\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "",	/* float_conv_to_ovf_u1_un */
	"\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "",	/* float_conv_to_ovf_u2_un */
	"\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "",	/* float_conv_to_ovf_u4_un */
	"\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "",	/* float_conv_to_ovf_u8_un */
	"\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "",	/* float_conv_to_ovf_i_un */
	"\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "",	/* float_conv_to_ovf_u_un */
	"\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "",	/* float_conv_to_ovf_i1 */
	"\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "",	/* float_conv_to_ovf_u1 */
	"\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "",	/* float_conv_to_ovf_i2 */
	"\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "",	/* float_conv_to_ovf_u2 */
	"\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "",	/* float_conv_to_ovf_i4 */
	"\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "",	/* float_conv_to_ovf_u4 */
	"\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "",	/* float_conv_to_ovf_i8 */
	"\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "",	/* float_conv_to_ovf_u8 */
	"iff\x0" "\x0" "\x0" "\x0" "\x0" "\x10" "",	/* float_ceq */
	"iff\x0" "\x0" "\x0" "\x0" "\x0" "\x10" "",	/* float_cgt */
	"iff\x0" "\x0" "\x0" "\x0" "\x0" "\x14" "",	/* float_cgt_un */
	"iff\x0" "\x0" "\x0" "\x0" "\x0" "\x10" "",	/* float_clt */
	"iff\x0" "\x0" "\x0" "\x0" "\x0" "\x14" "",	/* float_clt_un */
	NULL,	/* float_ceq_membase */
	NULL,	/* float_cgt_membase */
	NULL,	/* float_cgt_un_membase */
	NULL,	/* float_clt_membase */
	NULL,	/* float_clt_un_membase */
	"if\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x24" "",	/* float_conv_to_u */
	NULL,	/* group */
	"i\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x8" "",	/* aot_const */
	NULL,	/* patch_info */
	NULL,	/* got_entry */
	NULL,	/* unboxcast */
	"\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\xc" "",	/* call_handler */
	"\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x14" "",	/* start_handler */
	"\x0" "i\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x10" "",	/* op_endfilter */
	"lii\x0" "\x0" "\x0" "\x0" "\x0" "\x8" "",	/* op_bigmul */
	"lii\x0" "\x0" "\x0" "\x0" "\x0" "\x8" "",	/* op_bigmul_un */
	"iii\x0" "\x0" "\x0" "\x0" "\x0" "\x4" "",	/* adc */
	"ii\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\xc" "",	/* adc_imm */
	"iii\x0" "\x0" "\x0" "\x0" "\x0" "\x4" "",	/* sbb */
	"ii\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\xc" "",	/* sbb_imm */
	"iii\x0" "\x0" "\x0" "\x0" "\x0" "\x4" "",	/* addcc */
	"ii\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\xc" "",	/* addcc_imm */
	"iii\x0" "\x0" "\x0" "\x0" "\x0" "\x4" "",	/* subcc */
	"ii\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\xc" "",	/* subcc_imm */
	"\x0" "i\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x8" "",	/* br_reg */
	NULL,	/* sext_i1 */
	NULL,	/* sext_i2 */
	NULL,	/* sext_i4 */
	NULL,	/* zext_i1 */
	NULL,	/* zext_i2 */
	NULL,	/* zext_i4 */
	NULL,	/* cne */
	"iii\x0" "\x0" "\x0" "\x0" "\x0" "\x10" "",	/* add_ovf_carry */
	"iii\x0" "\x0" "\x0" "\x0" "\x0" "\x10" "",	/* sub_ovf_carry */
	"iii\x0" "\x0" "\x0" "\x0" "\x0" "\x10" "",	/* add_ovf_un_carry */
	"iii\x0" "\x0" "\x0" "\x0" "\x0" "\x10" "",	/* sub_ovf_un_carry */
	NULL,	/* sin */
	NULL,	/* cos */
	NULL,	/* abs */
	NULL,	/* tan */
	NULL,	/* atan */
	"ff\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x4" "",	/* sqrt */
	NULL,	/* getchar */
	NULL,	/* str_char_addr */
	NULL,	/* strlen */
	NULL,	/* gettype */
	NULL,	/* gethashcode */
	NULL,	/* getldelema2 */
	NULL,	/* memcpy */
	NULL,	/* memset */
	NULL,	/* cisinst */
	NULL,	/* ccastclass */
	NULL,	/* save_lmf */
	NULL,	/* restore_lmf */
	"i\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x8" "",	/* tls_get */
	NULL,	/* load_gotaddr */
	NULL,	/* dummy_use */
	NULL,	/* dummy_store */
	NULL,	/* not_reached */
	NULL,	/* atomic_add_i4 */
	NULL,	/* atomic_add_new_i4 */
	NULL,	/* atomic_add_imm_i4 */
	NULL,	/* atomic_add_imm_new_i4 */
	NULL,	/* atomic_exchange_i4 */
	NULL,	/* atomic_add_i8 */
	NULL,	/* atomic_add_new_i8 */
	NULL,	/* atomic_add_imm_i8 */
	NULL,	/* atomic_add_imm_new_i8 */
	NULL,	/* atomic_exchange_i8 */
	"\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x4" "",	/* memory_barrier */
	"ii\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x4" "",	/* arm_rsbs_imm */
	"ii\x0" "\x0" "\x0" "\x0" "\x0" "\x0" "\x4" "",	/* arm_rsc_imm */
};

