#!/bin/sh
# This should probably go into ifupdown
# But usually only those with lots of interfaces (vlans) need these
if [ -d "/proc/sys/net/ipv4/conf/$IFACE" ]
then
	if [ -n "$IF_IP_PROXY_ARP" ]; then
		if [ "$IF_IP_PROXY_ARP" -eq "1" ]; then
			echo 1 > "/proc/sys/net/ipv4/conf/$IFACE/proxy_arp"
		else
			echo 0 > "/proc/sys/net/ipv4/conf/$IFACE/proxy_arp"
		fi
	fi
	if [ -n "$IF_IP_RP_FILTER" ]; then
		if [ "$IF_IP_RP_FILTER" -eq "0" ]; then
			echo 0 > "/proc/sys/net/ipv4/conf/$IFACE/rp_filter"
		else
			echo 1 > "/proc/sys/net/ipv4/conf/$IFACE/rp_filter"
		fi
	fi
fi

