#! /bin/sh
#
# umountfs    Turn off swap and unmount all local filesystems.
#

PATH=/sbin:/bin:/usr/sbin:/usr/bin

# We leave /proc mounted.
echo "Unmounting local filesystems..."
grep -q /mnt/ram /proc/mounts && mount -o remount,ro /mnt/ram

mount -o remount,ro /

: exit 0
