Index: qemu/Makefile
===================================================================
--- qemu.orig/Makefile	2007-07-30 18:25:50.000000000 +0200
+++ qemu/Makefile	2007-07-30 18:26:13.000000000 +0200
@@ -5,14 +5,14 @@
 .PHONY: all clean distclean dvi info install install-doc tar tarbin \
 	speed test test2 html dvi info
 
-CFLAGS=-Wall -O2 -g -fno-strict-aliasing -I.
+CFLAGS+=-Wall -O2 -g -fno-strict-aliasing -I.
 ifdef CONFIG_DARWIN
 CFLAGS+= -mdynamic-no-pic
 endif
 ifeq ($(ARCH),sparc)
 CFLAGS+=-mcpu=ultrasparc
 endif
-LDFLAGS=-g
+LDFLAGS+=-g
 LIBS=
 DEFINES+=-D_GNU_SOURCE -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE
 TOOLS=qemu-img$(EXESUF)
Index: qemu/Makefile.target
===================================================================
--- qemu.orig/Makefile.target	2007-07-30 18:27:17.000000000 +0200
+++ qemu/Makefile.target	2007-07-30 18:27:23.000000000 +0200
@@ -17,9 +17,9 @@
 VPATH+=:$(SRC_PATH)/linux-user
 DEFINES+=-I$(SRC_PATH)/linux-user -I$(SRC_PATH)/linux-user/$(TARGET_ARCH)
 endif
-CFLAGS=-Wall -O2 -g -fno-strict-aliasing
+CFLAGS+=-Wall -O2 -g -fno-strict-aliasing
 #CFLAGS+=-Werror
-LDFLAGS=-g
+LDFLAGS+=-g
 LIBS=
 HELPER_CFLAGS=$(CFLAGS)
 DYNGEN=../dyngen$(EXESUF)
