DESCRIPTION = "Virtual package including the whole gEDA suite"
LICENSE = "GPLv2"
HOMEPAGE = "http://www.gpleda.org/"
PACKAGE_ARCH = "all"
PR = "r1"

DEPENDS = "libgeda gtk+"
DEPENDS += "geda-utils geda-gattrib geda-gnetlist geda-gschem geda-gsymcheck geda-symbols geda-docs geda-examples pcb"
RDEPENDS = "geda-utils geda-gattrib geda-gnetlist geda-gschem geda-gsymcheck geda-symbols pcb"
RRECOMMENDS = "geda-docs geda-examples"
ALLOW_EMPTY_${PN} = "1"
