# Makefile for UcSlugC
# Licensed under the GPL v2 or later
DISTRO=ucslugc
TARGET=openslug-packages

include common/Make.rules

# The following is required for bootstrapping
common/Make.rules:
	make -f ../common/Make.rules common
