NYLON_FEED = " \
base-files \
bash \
binutils \
bridge-utils \
busybox \
chillispot \
dash \
ddclient \
dnsmasq \
elvis \
gdb \
gnupg \
hostap-modules \
hostap-utils \
hostap-daemon \
htb-init \
ifplugd \
initscripts \
iperf \
ipkg \
iptables \
ksymoops \
less \
linux-hotplug \
lsof \
madwifi-modules \
maradns \
minicom \
mobilemesh \
modutils \
mtd-utils \
mtr \
nano \
ncurses \
netbase \
netperf \
ntp \
nylon-scripts \
nylon-statistics \
olsrd \
openssh \
pciutils \
pcmcia-cs \
perl \
pmacct \
ppp \
pptp-linux \
rrdtool \
ser \
shorewall \
stunnel \
sysvinit \
tcl \
tcpdump \
tinc \
tzdata \
usbutils \
vtun \
wireless-tools \
wpa-supplicant \
yamonenv \
"

# TODO:
# strace: SYS_read?
# gdb-cross: install paths, sdk?
# screen: sgttyb?

#kismet \
#
