#!/bin/sh

. /etc/init.d/functions

case "$1" in
    start)
    # We don't want this script to block the rest of the boot process
    if [ "$2" != "background" ]; then
	$0 $1 background &
    else
	. /etc/profile

	echo "Starting FBProgress"
	fbprogress.sh &
    fi 
    ;;

    stop)
    echo "Stopping FBProgress"
    killproc fbprogress.sh
    ;;

    restart)
    $0 stop
    sleep 1
    $0 start
    ;;

    *)
    echo "usage: $0 { start | stop | restart }"
    ;;
esac

exit 0
