#!/bin/sh

if [ ! $LAUNCHER_CLASS ]; then
  if [ $# -lt 2 ]; then
    echo "Usage :"
    echo "  $(basename $0) <classpath> <midlet-class> [midlet-name]"
    echo "  $(basename $0) -jar <jar-file>"
    exit 1
  fi

  LAUNCHER_CLASS=org.thenesis.midpath.main.MIDletLauncherSE

  # Add the MIDlet jar to the classpath  (must be loaded by the main classloader)
  if [ $1 = "-jar" ]; then
    CP=$2
    ARGS="$1 $2"
  else
    CP=$1
    ARGS="$2 $3"
  fi
else
  ARGS="$@"
fi

if [ ! $JAVA ]; then
  JAVA=java-cdc
fi

JAR_HOME=/usr/share/java

MIDPATH_HOME=/usr/share/midpath

CVM_HOME=/usr/lib/jvm/phoneme-advanced-foundation

JLP=/usr/lib/jni

# Set the classpath
CP=$CP:\
$MIDPATH_HOME/configuration:\
$MIDPATH_HOME/midpath.jar:\
$MIDPATH_HOME/microbackend.jar:\
$MIDPATH_HOME/sdljava-cldc.jar:\
$MIDPATH_HOME/escher-cldc.jar:\
$MIDPATH_HOME/jlayerme-cldc.jar:\
$MIDPATH_HOME/jorbis-cldc.jar:\
$MIDPATH_HOME/avetanabt-cldc.jar:\
$MIDPATH_HOME/jgl-cldc.jar:\
$MIDPATH_HOME/jsr172-jaxp.jar:\
$MIDPATH_HOME/jsr172-jaxrpc.jar:\
$MIDPATH_HOME/jsr239-opengles-jgl.jar:\
$MIDPATH_HOME/jsr239-opengles-core.jar:\
$MIDPATH_HOME/jsr239-opengles-nio.jar:\
$MIDPATH_HOME/jsr184-m3g.jar:\
$MIDPATH_HOME/jsr205-messaging.jar:\
$MIDPATH_HOME/jsr179-location.jar:\
$MIDPATH_HOME/jsr226-svg-core.jar:\
$MIDPATH_HOME/jsr226-svg-midp2.jar:\
$CVM_HOME/lib/foundation.jar:\
$CVM_HOME/lib/btclasses.zip:\
$JAR_HOME/microemu-nokiaui.jar:\
$JAR_HOME/microemu-siemensapi.jar:\
$JAR_HOME/kxml2.jar:\
$JAR_HOME/xmlpull.jar:\
$JAR_HOME/swt.jar

# Add whatever is mentioned in the CLASSPATH environment variable
if [ $CLASSPATH ]
then
  CP=$CP:$CLASSPATH
fi

$JAVA -cp $CP -Djava.library.path=$JLP $LAUNCHER_CLASS $ARGS

