--- snes9x-1.43-dev-src/snes9x/Makefile.in.old	2004-10-02 17:34:58.000000000 +0100
+++ snes9x-1.43-dev-src/snes9x/Makefile.in	2004-10-02 17:42:25.000000000 +0100
@@ -142,7 +142,7 @@
 #INCLUDES = -I../zlib @XINCLUDES@
 INCLUDES = @XINCLUDES@
 
-OPTIMISE = @OPTIMIZE@
+OPTIMISE = $(filter-out @OPTIMIZE@,-pedantic)
 
 #OPTIMISE=-g -fno-exceptions
 
@@ -165,7 +165,7 @@
 $(KREEDDEFINES) \
 $(SDD1DEFINES) \
 $(JOYDEFINES) \
--DNO_INLINE_SET_GET @SYSDEFINES@
+-DNO_INLINE_SET_GET @SYSDEFINES@ $(OECFLAGS)
 
 #-DOLD_COLOUR_BLENDING
 #-DSOUND
@@ -204,15 +204,15 @@
 #ggisnes9x
 #xf86snes9x
 
-offsets: offsets.o
-	$(CCC) $(INCLUDES) -o $@ offsets.o
+offsets: offsets.cpp
+	$(BUILD_CXX) $(INCLUDES) -o $@ $<
 	./offsets >i386/offsets.h
 
 #../zlib/libz.a:
 #	cd ../zlib && sh ./configure && make
 
 snes9x: $(OBJECTS) unix/x11.o $(AIDOOBJS) $(GUIOBJS)
-	$(CCC) $(INCLUDES) -o $@ $(OBJECTS) $(AIDOOBJS) $(GLIDEOBJS) $(OPENGLOBJS) unix/x11.o $(GUIOBJS) $(LDLIBS) $(GLIDELIBS) $(OPENGLLIBS) $(GUILIBS) @SYSLIBS@ -lXext -lX11 $(EXTRALIBS) -lm
+	$(CCC) $(INCLUDES) -o $@ $(OBJECTS) $(AIDOOBJS) $(GLIDEOBJS) $(OPENGLOBJS) unix/x11.o $(GUIOBJS) $(OELDFLAGS) $(LDLIBS) $(GLIDELIBS) $(OPENGLLIBS) $(GUILIBS) @SYSLIBS@ -lXext -lX11 $(EXTRALIBS) -lm
 
 ssnes9x: $(OBJECTS) unix/svga.o 
 	$(CCC) $(INCLUDES) -o $@ $(OBJECTS) $(GLIDEOBJS) unix/svga.o $(LDLIBS) $(GLIDELIBS) -lvga -lvgagl $(EXTRALIBS) -lm
