#!/bin/sh
#
# pulseaudio	This shell script starts and stops pulseaudio.
#
# chkconfig: 345 90 40
# description: Pulseaudio manages the sound input/output
# processname: pulseaudio

# Source function library.
#. /etc/rc.d/init.d/functions

RETVAL=0
prog="pulseaudio"

start() {
    echo -n "Starting the audio server..."
    # FIXME once alsa/shm permissions have been fixed, supply --system
	pulseaudio --resample-method=trivial -D -nF /etc/pulse/session
	echo $prog
}

stop() {
	# Stop daemons.
	echo -n "Shutting down $prog: "
	killall pulseaudio
    echo "done"
}

# See how we were called.
case "$1" in
  start)
	start
	;;
  stop)
	stop
	;;
  restart|reload)
	stop
	start
	;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $RETVAL
