diff -ur mahjongg_V1.0.0.orig/tools/Makefile mahjongg_V1.0.0/tools/Makefile
--- mahjongg_V1.0.0.orig/tools/Makefile	2004-06-16 20:55:06.000000000 +0200
+++ mahjongg_V1.0.0/tools/Makefile	2004-06-16 20:55:30.000000000 +0200
@@ -1,8 +1,8 @@
 all: bin2c layout2c
 
 bin2c: bin2c.c
-	gcc -O2 -Wall -o bin2c bin2c.c
+	$(BUILD_CC) -O2 -Wall -o bin2c bin2c.c
 
 layout2c: layout2c.c
-	gcc -O2 -Wall -o layout2c layout2c.c
+	$(BUILD_CC) -O2 -Wall -o layout2c layout2c.c
 
