#!/bin/sh

# Only if there's no mouse at all, we use use transparent cursors
# for stylus use comfort.
if ! ls /dev/input/mouse* >/dev/null 2>&1; then
    echo "Xcursor.theme: xcursor-transparent" | xrdb -merge -nocpp
fi
