#!/bin/bash

#$Header$

CONFFILE=/etc/dhcp-fwd.cfg
DAEMON=/usr/sbin/dhcp-fwd

case "$1" in
	start)
		start-stop-daemon -S -x $DAEMON -- -c $CONFFILE
		;;
	stop)
		start-stop-daemon -K -x $DAEMON
		;;
	restart | force-reload)
		$0 stop
		sleep 2
		$0 start
		;;
	*)
		echo "Usage: $0 {start|stop|restart|force-reload}"
		exit 1 
esac

exit 0
