#!/bin/sh
#
# Copyright (C) 2004 by Oleg I. Vdovikin <oleg@cs.msu.su>
# Modified for Unslung by Rod Whitby
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA 02111-1307 USA
#

if [ -f /share/flash/data/resling.tar.gz ] ; then
    RESLING=/share/flash/data/resling.tar.gz
elif   [ -f /share/hdd/data/resling.tar.gz ] ; then
    RESLING=/share/hdd/data/resling.tar.gz
elif [ -f /share/flash/conf/resling.tar.gz ] ; then
    RESLING=/share/flash/conf/resling.tar.gz
elif   [ -f /share/hdd/conf/resling.tar.gz ] ; then
    RESLING=/share/hdd/conf/resling.tar.gz
else
    RESLING=/share/flash/data/resling.tar.gz
fi

case "$1" in
	start)
		if [ -f ${RESLING} ]; then
			tar -C / -zxf ${RESLING}
		fi
		;;
	clear)
		rm -f ${RESLING}
		;;
	load)
		tar -C / -zxvf ${RESLING}
		;;
	list)
		tar -C / -ztf ${RESLING}
		;;
	save)
		[ -f /unslung/.files ] && FILES=$(cat /unslung/.files)
		rm -f /tmp/resling.tar.gz
		tar -C / -zcvf /tmp/resling.tar.gz /unslung $FILES && 
		rm -f ${RESLING} &&
		mv /tmp/resling.tar.gz ${RESLING} &&
		ls -l ${RESLING} &&
		echo "Saved."
		;;
	*)
		echo "Usage: $0 start|clear|load|list|save"
		;;
esac
