#!/bin/sh -e

case "$1" in
	start|restart)
		if [ -e /etc/network/run/ifstate ]; then
			echo -n "Cleaning: /etc/network/run/ifstate"
			echo -n >/etc/network/run/ifstate
			echo "."
		fi
		;;
	stop|reload|force-reload)
		;;
esac
