# Common description for Atmel ARM processors with LCD controller

include conf/machine/include/AT91.inc

MACHINE_FEATURES += "screen touchscreen keyboard"

# Some options we disable for now
# MACHINE_FEATURES += "apm"
# MACHINE_FEATURES += "lcd"
# MACHINE_FEATURES += "bluetooth wifi irda phone gps"
# MACHINE_FEATURES += "mmc mmcroot fat"
# MACHINE_FEATURES += "i2c spi serial"
# MACHINE_FEATURES += "sound libogg libvorbis"


