#!/bin/sh
#
# Wrapper which (almost) silently restarts the VM in case of segfaults.

redo_from_start=1;
while [ $redo_from_start -eq 1 ]; do
    echo "Running JamVM-native: ${@}"
    redo_from_start=0;
    jamvm ${1+"$@"}
    if [ $? -eq 139 ]; then
        echo "JamVM-native crashed - silently trying again"
        redo_from_start=1;
    fi
done

