#!/bin/sh

set -e

if [ -f /usr/bin/qtdemo ]; then
	QTDEMO=qtdemo
else
	QTDEMO="qtdemoE -qws"
fi

case "$1" in
  start)
	echo "Starting qtdemo"
	if [ -f /etc/profile.d/tslib.sh ]; then
		source /etc/profile.d/tslib.sh
	fi
	if [ -e $TSLIB_TSDEVICE ]; then
		if [ ! -f /etc/pointercal ]; then
			/usr/bin/ts_calibrate
		fi
		QWS_MOUSE_PROTO=tslib:$TSLIB_TSDEVICE $QTDEMO &
	else
		$QTDEMO &
	fi
	;;
  stop)
	echo "Stopping qtdemo"
	killall qtdemoE
	;;
  restart)
	$0 stop
	$0 start
	;;
  *)
	echo "usage: $0 { start | stop | restart }" >&2
	exit 1
	;;
esac

exit 0
