#! /bin/sh
#
# This is an init script for openembedded
# Copy it to /etc/init.d/transmission and type
# > update-rc.d transmission defaults 60
#
# 



# Exit if the package is not installed
test -f /usr/bin/transmission-daemon || exit 0

SSDOPTIONS="--chuid transmission:transmission"

case "$1" in
  start)
    echo  "Starting transmission-daemon"
    /sbin/start-stop-daemon $SSDOPTIONS --start --quiet --exec /usr/bin/transmission-daemon -- -w /home/transmission -g /home/transmission/.config
    ;;
  stop)
    echo  "Stopping transmission-daemon"
    /sbin/start-stop-daemon --stop --quiet --exec /usr/bin/transmission-daemon
    ;;
  restart)
    echo -n "Stopping transmission-daemon"
    /sbin/start-stop-daemon --stop --quiet --exec /usr/bin/transmission-daemon
    for i in 1 2 3 ;
    do
        sleep 1
        echo -n "."
    done
    echo  "Restarting transmission-daemon" 
    /sbin/start-stop-daemon $SSDOPTIONS --start --quiet --exec /usr/bin/transmission-daemon -- -w /home/transmission -g /home/transmission/.config
    ;;
  *)
    echo "Usage: /etc/init.d/tranmission {start|stop|restart}"
    exit 1
esac

exit 0
