
# version 4.4.x requires perl + some perl modules
RDEPENDS_${PN} += "\
    perl \
    perl-module-lib \
    perl-module-autouse \
    perl-module-cwd \
    perl-module-file-basename \
    perl-module-file-temp \
    perl-module-getopt-long \
    perl-module-carp \
    perl-module-findbin \
    perl-module-file-spec-unix \
    perl-module-scalar-util \
    perl-module-io \
    perl-module-io-handle \
    perl-module-exporter-heavy \
    perl-module-list-util \
    perl-module-socket \
"
