#!/bin/sh

mounted=

/bin/mount -t proc proc /proc
/bin/echo "0x0100" > /proc/sys/kernel/real-root-dev

if [ -z "$mounted" ] && /bin/mount -rt jffs2 /dev/mtdblock4 /mnt/tmpmnt ; then

    if  [ -x /mnt/tmpmnt/sbin/init -o -x /mnt/tmpmnt/bin/init ] ; then
	/bin/echo "Root filesystem will be mounted from /dev/mtdblock4 ..."
	mounted=/mnt/tmpmnt
	/bin/echo "0x1f04" > /proc/sys/kernel/real-root-dev
    fi

    /bin/umount /mnt/tmpmnt
fi

if [ -z "$mounted" ] ; then

    if  [ -x /mnt/tmpmnt/sbin/init -o -x /mnt/tmpmnt/bin/init ] ; then
	/bin/echo "Root filesystem will be mounted from /dev/ram0 ..."
	mounted=/mnt/tmpmnt
	/bin/echo "0x0100" > /proc/sys/kernel/real-root-dev
    fi
fi

if [ -z "$mounted" ] ; then
    /bin/echo "Root filesystem cannot be found - dropping into shell ..."

    /bin/echo "5" > /proc/sys/kernel/panic

    device=/dev/`/bin/sed -n -e 's/^\(mtd[0-9]*\): .* "FIS directory"/\1/p' /proc/mtd`   
    length=`/bin/dd if=$device bs=2 skip=2048 | /bin/hexdump -n 4 -e '4/1 "%02X"' $device`

    if ( [ "$length" != "FFFFFFFF" ] ); then
	/bin/dd if=$device bs=2 skip=2056 | /bin/tar zxvf -
	/sbin/insmod ixp400
	/sbin/insmod ixp425_eth
	/sbin/ifconfig ixp0 up 192.168.1.77 netmask 255.255.0.0
	/sbin/telnetd
    fi

    exec /bin/sh
fi

/bin/umount /proc

exit 0
