#!/bin/sh
#

[ -z $LOGNAME ] && export LOGNAME=root && export HOME=/root
[ -z $HOME ] && export HOME=/$LOGNAME

export QTDIR=/opt/QtPalmtop
export OPIEDIR=/opt/QtPalmtop
export QPEDIR=/opt/QtPalmtop
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$OPIEDIR/lib
export PATH=$PATH:$OPIEDIR/bin

if [ -e /proc/cpuinfo ] ; then
	model=`grep "^Hardware" /proc/cpuinfo | sed -e "s/.*: *//" | tr a-z A-Z`
	
	case "$model" in	
	"HP IPAQ H3100" | "HP IPAQ H3800" )
		QWS_DISPLAY=Transformed:Rot90:0 ;;
	"HP IPAQ H5400" | "HP JORNADA 56X" | "HP IPAQ H2200" | "SHARP Tosa")
		QWS_DISPLAY=Transformed:Rot0:0 ;;
	*SIMPAD* )
		QWS_KEYBOARD='SIMpad'
		QWS_DISPLAY=Transformed:Rot0:0 ;;
	RAMSES )
		# already set based on /proc/sys/board/lcd_type
		test -z "$QWS_DISPLAY" && QWS_DISPLAY=Transformed:Rot90:0
		;;
	*)
		QWS_DISPLAY=Transformed:Rot270:0 ;;
	esac
else
	QWS_DISPLAY=Transformed:Rot270:0
fi
export QWS_DISPLAY

if [ ! -x $OPIEDIR/bin/qpe ] ; then 
	echo Opie not installed
	exit 0  
fi

. /etc/profile

case $1 in
'start')
	cd $HOME
	rm -f /etc/rc2.d/S99x # Can't have both running!
	
	if [ -x $OPIEDIR/bin/opie-login ]; then
		if ! killall -0 syslogd 2>/dev/null >/dev/null; then
			echo Starting Opie-login....
			$OPIEDIR/bin/opie-login 2>/dev/null >/dev/null &
		else
			echo Starting Opie-login with syslog logging.....
			( $OPIEDIR/bin/opie-login  2>&1 | logger ) &
		fi
	else
		$OPIEDIR/bin/opie-reorgfiles
		if [ -x /usr/bin/ssh-agent ]; then
			 SSHAGENT=/usr/bin/ssh-agent
		else
			 SSHAGENT=""
		fi
		
		if [ -x $OPIEDIR/bin/opie-sh-ssh-askpass.sh ]; then
			export SSH_ASKPASS=$OPIEDIR/bin/opie-sh-ssh-askpass.sh
		fi
			
		if ! killall -0 syslogd 2>/dev/null >/dev/null; then
			echo Starting Opie....
			$SSHAGENT $OPIEDIR/bin/qpe 2>/dev/null >/dev/null &
		else
			echo Starting Opie with syslog logging.....
			( $SSHAGENT $OPIEDIR/bin/qpe 2>&1 | logger ) &
		fi
	fi
	;;

'stop')
	echo "Killing Opie..."
	killall qpe
	killall opie-login
	;;

*)
	echo "usage: $0 { start | stop }"
	;;

esac
