--- atmelwlandriver/src/Pcmcia_Pci/Makefile~	2004-06-05 05:11:18.000000000 +0100
+++ atmelwlandriver/src/Pcmcia_Pci/Makefile	2004-07-03 17:23:35.000000000 +0100
@@ -72,11 +72,11 @@
 	@for i in $(PCMCIA-y); do make $$i || exit 1; done
 
 final: $(objs) $(DEBUGORNO) fastvnet_cs.o
-	ld -r -o $(OBJDIR)/$(MODULE).o fastvnet_cs.o $(DEBUGORNO) $(objs)
+	$(LD) -r -o $(OBJDIR)/$(MODULE).o fastvnet_cs.o $(DEBUGORNO) $(objs)
 	nm $(OBJDIR)/$(MODULE).o |sort -u >$(OBJDIR)/$(patsubst %.o,%.map,$(MODULE).o); 
 ifeq 	'$(NEW_KERN)' 'y'
 	$(CC) $(MODOFLAGS) -c -o $(OBJDIR)/$(MAGICMOD).o $(MAGICMOD).c
-	ld -r -o $(OBJDIR)/$(MODULE).ko $(OBJDIR)/$(MODULE).o $(OBJDIR)/$(MAGICMOD).o
+	$(LD) -r -o $(OBJDIR)/$(MODULE).ko $(OBJDIR)/$(MODULE).o $(OBJDIR)/$(MAGICMOD).o
 endif
 
 rfmdD:
